/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const voxelShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'vec3'; iColor: 'vec3' }, { uViewProj: 'mat4'; uLightDir: 'vec3'; uFog: 'vec3'; uCamPos: 'vec3'; uFogDist: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uLightDir : vec3f,
  uFog : vec3f,
  uCamPos : vec3f,
  uFogDist : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : vec3f,
  @location(4) iColor : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vColor : vec3f,
  @location(2) vFog : f32,
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = bm_in.aPosition * bm_in.iScale + bm_in.iOffset;
  bm_out.vNormal = bm_in.aNormal;
  bm_out.vColor = bm_in.iColor;
  bm_out.vFog = clamp(length(world - bm_u.uCamPos) / bm_u.uFogDist, 0.0, 1.0);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let n = normalize(bm_in.vNormal);
  let ambient = hemisphereLight(n, vec3f(0.3, 0.36, 0.48), vec3f(0.09, 0.07, 0.08));
  let key = lambert(n, bm_u.uLightDir);
  let lit = bm_in.vColor * (ambient + vec3f(1.0, 0.72, 0.45) * (key * 0.95));
  return vec4f(mix(lit, bm_u.uFog, bm_in.vFog * 0.92), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iColor: 'vec3' },
  uniforms: { uViewProj: 'mat4', uLightDir: 'vec3', uFog: 'vec3', uCamPos: 'vec3', uFogDist: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iColor","type":"vec3","location":4,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uFog","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uFogDist","type":"float","kind":"1f","size":1,"offset":108}],"uniformBlockSize":112},

};

export default voxelShader;
