/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const contactShadowShader: CompiledShader<{ aPosition: 'vec3' }, { iOffset: 'vec3'; iScale: 'vec3'; iColor: 'vec3' }, { uViewProj: 'mat4'; uBillboard: 'sampler2D' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uBillboard : texture_2d<f32>;
@group(0) @binding(2) var uBillboard_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iOffset : vec3f,
  @location(2) iScale : vec3f,
  @location(3) iColor : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vLocal : vec2f,
  @location(1) vColor : vec3f,
  @location(2) vRadius : f32,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn channelToDisplay(channel : f32) -> f32 {
  let safe = max(channel, 0.0);
  let low = safe * 12.92;
  let high = pow(safe, 0.4166666666666667) * 1.055 - 0.055;
  return mix(low, high, step(0.0031308, safe));
}
fn encodeSrgb(color : vec3f) -> vec3f {
  return vec3f(channelToDisplay(color.x), channelToDisplay(color.y), channelToDisplay(color.z));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let rotated = rotate2(bm_in.aPosition.xz * bm_in.iScale.xz, bm_in.iScale.y);
  let world = vec3f(rotated.x + bm_in.iOffset.x, bm_in.iOffset.y, rotated.y + bm_in.iOffset.z);
  bm_out.vLocal = bm_in.aPosition.xz;
  bm_out.vColor = bm_in.iColor;
  bm_out.vRadius = bm_in.iScale.x;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let falloff = smoothstep(1.0, 0.12, length(bm_in.vLocal));
  let present = smoothstep(0.0, 0.02, bm_in.vRadius);
  let structure = textureSample(uBillboard, uBillboard_sampler, bm_in.vLocal * 0.5 + vec2f(0.5, 0.5)).w;
  return vec4f(encodeSrgb(bm_in.vColor), falloff * 0.6 * present * (0.62 + structure * 0.38));
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iColor: 'vec3' },
  uniforms: { uViewProj: 'mat4', uBillboard: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iColor","type":"vec3","location":3,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uBillboard","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":64},

};

export default contactShadowShader;
