/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const foundryGlowShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'float'; iColor: 'vec3'; iPower: 'float' }, { uViewProj: 'mat4'; uCameraPosition: 'vec3' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : f32,
  @location(4) iColor : vec3f,
  @location(5) iPower : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vColor : vec3f,
  @location(3) vPower : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = bm_in.aPosition * bm_in.iScale + bm_in.iOffset;
  bm_out.vWorld = world;
  bm_out.vNormal = bm_in.aNormal;
  bm_out.vColor = bm_in.iColor;
  bm_out.vPower = bm_in.iPower;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let rim = pow(1.0 - max(dot(normalize(bm_in.vNormal), view), 0.0), 2.4);
  let strength = (0.3 + rim * 2.2) * (0.35 + bm_in.vPower * 0.2);
  return vec4f(bm_in.vColor * strength, 0.32 + rim * 0.55);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'float', iColor: 'vec3', iPower: 'float' },
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"float","location":3,"size":1,"divisor":1},{"name":"iColor","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iPower","type":"float","location":5,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64}],"uniformBlockSize":80},

};

export default foundryGlowShader;
