/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const foundryShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'vec3'; iBaseColor: 'vec3'; iMaterial: 'vec3' }, { uViewProj: 'mat4'; uModel: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float'; uEmberPosition: 'vec3'; uEmberColor: 'vec3'; uEmberPower: 'float'; uEmberRadius: 'float'; uIonPosition: 'vec3'; uIonColor: 'vec3'; uIonPower: 'float'; uIonRadius: 'float'; uVioletPosition: 'vec3'; uVioletColor: 'vec3'; uVioletPower: 'float'; uVioletRadius: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
  uEmberPosition : vec3f,
  uEmberColor : vec3f,
  uEmberPower : f32,
  uEmberRadius : f32,
  uIonPosition : vec3f,
  uIonColor : vec3f,
  uIonPower : f32,
  uIonRadius : f32,
  uVioletPosition : vec3f,
  uVioletColor : vec3f,
  uVioletPower : f32,
  uVioletRadius : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : vec3f,
  @location(4) iBaseColor : vec3f,
  @location(5) iMaterial : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vBaseColor : vec3f,
  @location(3) vMaterial : vec3f,
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn pointRadiance(world : vec3f, normal : vec3f, view : vec3f, lightPosition : vec3f, lightColor : vec3f, lightPower : f32, lightRadius : f32, roughness : f32, metalness : f32) -> vec3f {
  let toLight = lightPosition - world;
  let distanceSq = dot(toLight, toLight);
  let range = clamp(1.0 - distanceSq / (lightRadius * lightRadius), 0.0, 1.0);
  let attenuation = range * range;
  let light = normalize(toLight);
  let diffuse = max(dot(normal, light), 0.0);
  let specular = min(specGGX(normal, light, view, roughness), 2.4) * (0.16 + metalness * 0.84);
  return lightColor * (lightPower * attenuation * (diffuse + specular));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let local = bm_in.aPosition * bm_in.iScale;
  let world = (bm_u.uModel * vec4f(local, 1.0)).xyz + bm_in.iOffset;
  bm_out.vWorld = world;
  bm_out.vNormal = normalize((bm_u.uModel * vec4f(bm_in.aNormal, 0.0)).xyz);
  bm_out.vBaseColor = bm_in.iBaseColor;
  bm_out.vMaterial = bm_in.iMaterial;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = normalize(bm_in.vNormal);
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let roughness = clamp(bm_in.vMaterial.x, 0.08, 1.0);
  let metalness = clamp(bm_in.vMaterial.y, 0.0, 1.0);
  let ember = pointRadiance(bm_in.vWorld, normal, view, bm_u.uEmberPosition, bm_u.uEmberColor, bm_u.uEmberPower, bm_u.uEmberRadius, roughness, metalness);
  let ion = pointRadiance(bm_in.vWorld, normal, view, bm_u.uIonPosition, bm_u.uIonColor, bm_u.uIonPower, bm_u.uIonRadius, roughness, metalness);
  let violet = pointRadiance(bm_in.vWorld, normal, view, bm_u.uVioletPosition, bm_u.uVioletColor, bm_u.uVioletPower, bm_u.uVioletRadius, roughness, metalness);
  let radiance = ember + ion + violet;
  let sky = vec3f(0.07, 0.095, 0.15) * (0.38 + normal.y * 0.12);
  let lit = bm_in.vBaseColor * (sky + radiance * 0.82) + radiance * (metalness * 0.28);
  let pulse = 0.92 + sin(bm_u.uTime * 2.4 + bm_in.vWorld.x * 0.5) * 0.08;
  let emissive = bm_in.vBaseColor * (bm_in.vMaterial.z * pulse);
  let fog = smoothstep(9.0, 18.0, length(bm_u.uCameraPosition - bm_in.vWorld));
  let color = mix(lit + emissive, vec3f(0.008, 0.012, 0.025), fog * 0.72);
  return vec4f(tonemapACES(color), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iBaseColor: 'vec3', iMaterial: 'vec3' },
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uCameraPosition: 'vec3', uTime: 'float', uEmberPosition: 'vec3', uEmberColor: 'vec3', uEmberPower: 'float', uEmberRadius: 'float', uIonPosition: 'vec3', uIonColor: 'vec3', uIonPower: 'float', uIonRadius: 'float', uVioletPosition: 'vec3', uVioletColor: 'vec3', uVioletPower: 'float', uVioletRadius: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iBaseColor","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iMaterial","type":"vec3","location":5,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":140},{"name":"uEmberPosition","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uEmberColor","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uEmberPower","type":"float","kind":"1f","size":1,"offset":172},{"name":"uEmberRadius","type":"float","kind":"1f","size":1,"offset":176},{"name":"uIonPosition","type":"vec3","kind":"3fv","size":3,"offset":192},{"name":"uIonColor","type":"vec3","kind":"3fv","size":3,"offset":208},{"name":"uIonPower","type":"float","kind":"1f","size":1,"offset":220},{"name":"uIonRadius","type":"float","kind":"1f","size":1,"offset":224},{"name":"uVioletPosition","type":"vec3","kind":"3fv","size":3,"offset":240},{"name":"uVioletColor","type":"vec3","kind":"3fv","size":3,"offset":256},{"name":"uVioletPower","type":"float","kind":"1f","size":1,"offset":268},{"name":"uVioletRadius","type":"float","kind":"1f","size":1,"offset":272}],"uniformBlockSize":288},

};

export default foundryShader;
