/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const foundryGlowShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'float'; iColor: 'vec3'; iPower: 'float'; iPhase: 'float'; iMotion: 'float' }, { uBillboard: 'sampler2D'; uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uBillboard : texture_2d<f32>;
@group(0) @binding(2) var uBillboard_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : f32,
  @location(4) iColor : vec3f,
  @location(5) iPower : f32,
  @location(6) iPhase : f32,
  @location(7) iMotion : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vColor : vec3f,
  @location(3) vPower : f32,
}
fn channelToDisplay(channel : f32) -> f32 {
  let safe = max(channel, 0.0);
  let low = safe * 12.92;
  let high = pow(safe, 0.4166666666666667) * 1.055 - 0.055;
  return mix(low, high, step(0.0031308, safe));
}
fn encodeSrgb(color : vec3f) -> vec3f {
  return vec3f(channelToDisplay(color.x), channelToDisplay(color.y), channelToDisplay(color.z));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let drift = vec3f(sin(bm_u.uTime * (0.42 + bm_in.iMotion) + bm_in.iPhase) * 0.42 * bm_in.iMotion, sin(bm_u.uTime * (0.68 + bm_in.iMotion * 0.5) + bm_in.iPhase * 1.7) * 0.34 * bm_in.iMotion, cos(bm_u.uTime * (0.36 + bm_in.iMotion) + bm_in.iPhase) * 0.28 * bm_in.iMotion);
  let world = bm_in.aPosition * bm_in.iScale + bm_in.iOffset + drift;
  bm_out.vWorld = world;
  bm_out.vNormal = bm_in.aNormal;
  bm_out.vColor = bm_in.iColor;
  bm_out.vPower = bm_in.iPower * (1.0 + sin(bm_u.uTime * 2.2 + bm_in.iPhase) * 0.18 * bm_in.iMotion);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let rim = pow(1.0 - max(dot(normalize(bm_in.vNormal), view), 0.0), 2.4);
  let strength = (0.3 + rim * 2.2) * (0.35 + bm_in.vPower * 0.2);
  let surfaceNormal = normalize(bm_in.vNormal);
  let structure = textureSample(uBillboard, uBillboard_sampler, vec2f(surfaceNormal.x * 0.5 + 0.5, surfaceNormal.y * 0.5 + 0.5)).w;
  let textured = 0.55 + structure * 0.45;
  return vec4f(encodeSrgb(bm_in.vColor * (strength * textured)), (0.32 + rim * 0.55) * textured);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'float', iColor: 'vec3', iPower: 'float', iPhase: 'float', iMotion: 'float' },
  uniforms: { uBillboard: 'sampler2D', uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"float","location":3,"size":1,"divisor":1},{"name":"iColor","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iPower","type":"float","location":5,"size":1,"divisor":1},{"name":"iPhase","type":"float","location":6,"size":1,"divisor":1},{"name":"iMotion","type":"float","location":7,"size":1,"divisor":1}],"uniforms":[{"name":"uBillboard","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76}],"uniformBlockSize":80},

};

export default foundryGlowShader;
