/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const nightBackdropShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vWorld = bm_in.aPosition;
  bm_out.bm_position = bm_u.uViewProj * vec4f(bm_in.aPosition + bm_u.uCameraPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let direction = normalize(bm_in.vWorld);
  let height = clamp(direction.y, -1.0, 1.0);
  let haze = pow(1.0 - clamp(height, 0.0, 1.0), 6.0);
  let below = clamp(0.0 - height, 0.0, 1.0);
  let zenith = vec3f(0.0016, 0.0028, 0.0026);
  let horizon = vec3f(0.02, 0.042, 0.04);
  let seam = pow(max(1.0 - abs(height) * 9.0, 0.0), 2.0) * 0.012;
  let sky = zenith + (horizon - zenith) * haze + vec3f(seam, seam * 0.7, seam * 0.35);
  let ground = vec3f(0.014, 0.02, 0.018);
  return vec4f(sky * (1.0 - below) + ground * below, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76}],"uniformBlockSize":80},

};

export default nightBackdropShader;
