/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const postShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uScene: 'sampler2D'; uExposure: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uExposure : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uScene : texture_2d<f32>;
@group(0) @binding(2) var uScene_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn channelToDisplay(channel : f32) -> f32 {
  let safe = max(channel, 0.0);
  let low = safe * 12.92;
  let high = pow(safe, 0.4166666666666667) * 1.055 - 0.055;
  return mix(low, high, step(0.0031308, safe));
}
fn encodeSrgb(color : vec3f) -> vec3f {
  return vec3f(channelToDisplay(color.x), channelToDisplay(color.y), channelToDisplay(color.z));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = ((vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).xy / (vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).w * vec2f(0.5, -0.5) + vec2f(0.5));
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let scene = textureSample(uScene, uScene_sampler, bm_in.vUv).xyz;
  return vec4f(encodeSrgb(tonemapACES(scene * bm_u.uExposure)), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uScene: 'sampler2D', uExposure: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uScene","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uExposure","type":"float","kind":"1f","size":1,"offset":0}],"uniformBlockSize":16},

};

export default postShader;
