/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const reliquaryFloorShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uDiffuse: 'sampler2D'; uAo: 'sampler2D'; uRoughness: 'sampler2D'; uEmberPosition: 'vec3'; uEmberColor: 'vec3'; uEmberPower: 'float'; uEmberRadius: 'float'; uIonPosition: 'vec3'; uIonColor: 'vec3'; uIonPower: 'float'; uIonRadius: 'float'; uVioletPosition: 'vec3'; uVioletColor: 'vec3'; uVioletPower: 'float'; uVioletRadius: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uEmberPosition : vec3f,
  uEmberColor : vec3f,
  uEmberPower : f32,
  uEmberRadius : f32,
  uIonPosition : vec3f,
  uIonColor : vec3f,
  uIonPower : f32,
  uIonRadius : f32,
  uVioletPosition : vec3f,
  uVioletColor : vec3f,
  uVioletPower : f32,
  uVioletRadius : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uDiffuse : texture_2d<f32>;
@group(0) @binding(2) var uDiffuse_sampler : sampler;
@group(0) @binding(3) var uAo : texture_2d<f32>;
@group(0) @binding(4) var uAo_sampler : sampler;
@group(0) @binding(5) var uRoughness : texture_2d<f32>;
@group(0) @binding(6) var uRoughness_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vUv : vec2f,
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn materialPresentationFloorLight(world : vec3f, normal : vec3f, view : vec3f, lightPosition : vec3f, lightColor : vec3f, lightPower : f32, lightRadius : f32, roughness : f32) -> vec3f {
  let toLight = lightPosition - world;
  let distanceSq = dot(toLight, toLight);
  let range = clamp(1.0 - distanceSq / (lightRadius * lightRadius), 0.0, 1.0);
  let light = normalize(toLight);
  let diffuse = max(dot(normal, light), 0.0);
  let specular = specGGX(normal, light, view, roughness) * 0.12;
  return lightColor * (lightPower * range * range * (diffuse + specular));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = vec3f(bm_in.aPosition.x, -0.42, -bm_in.aPosition.y);
  bm_out.vWorld = world;
  bm_out.vUv = bm_in.aUv * vec2f(4.5, 3.35);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let diffuseSample = textureSample(uDiffuse, uDiffuse_sampler, bm_in.vUv).xyz;
  let ao = mix(0.48, 1.0, textureSample(uAo, uAo_sampler, bm_in.vUv).x);
  let roughness = clamp(textureSample(uRoughness, uRoughness_sampler, bm_in.vUv).x, 0.2, 0.98);
  let normal = vec3f(0.0, 1.0, 0.0);
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let amber = materialPresentationFloorLight(bm_in.vWorld, normal, view, bm_u.uEmberPosition, bm_u.uEmberColor, bm_u.uEmberPower, bm_u.uEmberRadius, roughness);
  let blue = materialPresentationFloorLight(bm_in.vWorld, normal, view, bm_u.uIonPosition, bm_u.uIonColor, bm_u.uIonPower, bm_u.uIonRadius, roughness);
  let plum = materialPresentationFloorLight(bm_in.vWorld, normal, view, bm_u.uVioletPosition, bm_u.uVioletColor, bm_u.uVioletPower, bm_u.uVioletRadius, roughness);
  let irradiance = amber + blue + plum;
  let dampEarth = diffuseSample * vec3f(0.58, 0.62, 0.55);
  let ambient = vec3f(0.055, 0.065, 0.06) * ao;
  let lit = dampEarth * (ambient + irradiance * 0.78);
  let stonePath = smoothstep(0.44, 0.5, max(0.6 - abs(bm_in.vWorld.x) * 0.12, 0.6 - abs(bm_in.vWorld.z) * 0.12));
  let pathTint = mix(vec3f(1.0, 1.0, 1.0), vec3f(0.74, 0.78, 0.72), stonePath * 0.18);
  return vec4f(tonemapACES(lit * pathTint + irradiance * 0.025), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uDiffuse: 'sampler2D', uAo: 'sampler2D', uRoughness: 'sampler2D', uEmberPosition: 'vec3', uEmberColor: 'vec3', uEmberPower: 'float', uEmberRadius: 'float', uIonPosition: 'vec3', uIonColor: 'vec3', uIonPower: 'float', uIonRadius: 'float', uVioletPosition: 'vec3', uVioletColor: 'vec3', uVioletPower: 'float', uVioletRadius: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uDiffuse","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uAo","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uRoughness","type":"sampler2D","kind":"1i","size":1,"unit":2,"textureBinding":5,"samplerBinding":6},{"name":"uEmberPosition","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uEmberColor","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uEmberPower","type":"float","kind":"1f","size":1,"offset":108},{"name":"uEmberRadius","type":"float","kind":"1f","size":1,"offset":112},{"name":"uIonPosition","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uIonColor","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uIonPower","type":"float","kind":"1f","size":1,"offset":156},{"name":"uIonRadius","type":"float","kind":"1f","size":1,"offset":160},{"name":"uVioletPosition","type":"vec3","kind":"3fv","size":3,"offset":176},{"name":"uVioletColor","type":"vec3","kind":"3fv","size":3,"offset":192},{"name":"uVioletPower","type":"float","kind":"1f","size":1,"offset":204},{"name":"uVioletRadius","type":"float","kind":"1f","size":1,"offset":208}],"uniformBlockSize":224},

};

export default reliquaryFloorShader;
