/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const luminousReefShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float'; uPointer: 'vec2' }> = {
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
  uPointer : vec2f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn hash21(p : vec2f) -> f32 {
  return fract(sin(dot(p, vec2f(127.1, 311.7))) * 43758.5453);
}
fn vnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  let a = hash21(cell);
  let b = hash21(cell + vec2f(1.0, 0.0));
  let c = hash21(cell + vec2f(0.0, 1.0));
  let d = hash21(cell + vec2f(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
fn fbm2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn voronoi2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  var minDist = 8.0;
  for (var i = -1.0; i <= 1.0; i = i + 1.0) {
    for (var j = -1.0; j <= 1.0; j = j + 1.0) {
      let neighbor = vec2f(i, j);
      let feature = hash22(cell + neighbor);
      let diff = neighbor + feature - f;
      minDist = min(minDist, length(diff));
    }
  }
  return minDist;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect + (bm_u.uPointer.x - 0.5) * 0.08, bm_in.vUv.y - 0.5 + (bm_u.uPointer.y - 0.5) * 0.04) * 2.35;
  let depth = smoothstep(0.8, -1.0, p.y);
  let waterNoise = fbm2(p * 2.2 + vec2f(bm_u.uTime * 0.035, -bm_u.uTime * 0.025), 5.0);
  let causticCells = voronoi2(p * 7.5 + vec2f(bm_u.uTime * 0.11, bm_u.uTime * 0.04));
  let caustics = smoothstep(0.18, 0.02, causticCells) * smoothstep(-0.9, 0.75, p.y);
  let leftJelly = length(vec2f((p.x + 0.58) * 1.1, (p.y - 0.12) * 1.45));
  let rightJelly = length(vec2f((p.x - 0.52) * 1.15, (p.y + 0.04) * 1.5));
  let jellyA = smoothstep(0.34, 0.27, leftJelly) + 0.025 / max(abs(leftJelly - 0.31), 0.012);
  let jellyB = smoothstep(0.29, 0.23, rightJelly) + 0.02 / max(abs(rightJelly - 0.26), 0.012);
  let seabed = smoothstep(0.05, -0.03, p.y + 0.73 + sin(p.x * 3.2) * 0.08);
  let coral = smoothstep(0.055, 0.015, abs(sin(p.x * 8.0 + p.y * 4.0))) * smoothstep(-0.3, -0.82, p.y) * (1.0 - seabed);
  let background = vec3f(0.002, 0.018, 0.045) + vec3f(0.005, 0.11, 0.16) * (depth * 0.8 + waterNoise * 0.34);
  let glow = vec3f(0.03, 0.9, 0.78) * (jellyA * (0.6 + sin(bm_u.uTime * 1.7) * 0.08)) + vec3f(0.34, 0.18, 1.2) * (jellyB * (0.62 + sin(bm_u.uTime * 1.3 + 2.0) * 0.1)) + vec3f(0.08, 0.52, 0.62) * (caustics * 0.36) + vec3f(0.03, 0.34, 0.23) * (coral * 0.7);
  let floorColor = vec3f(0.012, 0.035, 0.05) * seabed;
  return vec4f(tonemapACES(background + glow + floorColor), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float', uPointer: 'vec2' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4},{"name":"uPointer","type":"vec2","kind":"2fv","size":2,"offset":8}],"uniformBlockSize":16},

};

export default luminousReefShader;
