/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const townWaterFeaturesShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aUv: 'vec2'; aFeature: 'vec4' }, Record<string, never>, { uViewProj: 'mat4'; uLightViewProj: 'mat4'; uCamPos: 'vec3'; uLightDir: 'vec3'; uSunColor: 'vec3'; uSunIntensity: 'float'; uSkyColor: 'vec3'; uDeepColor: 'vec3'; uShallowColor: 'vec3'; uFoamColor: 'vec3'; uRoughness: 'float'; uTime: 'float'; uFogColor: 'vec3'; uFogStart: 'float'; uFogEnd: 'float'; uFogStrength: 'float'; uShadowMap: 'sampler2D'; uDetailNormal: 'sampler2D'; uShadowTexel: 'vec2'; uShadowBias: 'float'; uShadowStrength: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uLightViewProj : mat4x4f,
  uCamPos : vec3f,
  uLightDir : vec3f,
  uSunColor : vec3f,
  uSunIntensity : f32,
  uSkyColor : vec3f,
  uDeepColor : vec3f,
  uShallowColor : vec3f,
  uFoamColor : vec3f,
  uRoughness : f32,
  uTime : f32,
  uFogColor : vec3f,
  uFogStart : f32,
  uFogEnd : f32,
  uFogStrength : f32,
  uShadowTexel : vec2f,
  uShadowBias : f32,
  uShadowStrength : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uShadowMap : texture_2d<f32>;
@group(0) @binding(2) var uShadowMap_sampler : sampler;
@group(0) @binding(3) var uDetailNormal : texture_2d<f32>;
@group(0) @binding(4) var uDetailNormal_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aUv : vec2f,
  @location(3) aFeature : vec4f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vUv : vec2f,
  @location(3) vFeature : vec4f,
  @location(4) vSignal : f32,
  @location(5) vDepth : f32,
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
fn surfaceNormal(world : vec3f, time : f32, amplitude : f32) -> vec3f {
  let dx = cos(world.x * 2.1 + time * 0.85) * 1.176 + cos((world.x + world.z) * 3.2 + time * 1.13) * 0.448;
  let dz = cos(world.z * 1.7 - time * 0.72) * 0.51 + cos((world.x + world.z) * 3.2 + time * 1.13) * 0.448;
  return normalize(vec3f(-dx * amplitude, 1.0, -dz * amplitude));
}
fn fallingNormal(uvX : f32, uvY : f32, phase : f32, time : f32) -> vec3f {
  let crossSlope = cos(uvX * 12.0 + uvY * 7.0 - time * 5.4 + phase * 6.2831853) * 0.16 + cos(uvX * 29.0 - uvY * 4.0 - time * 8.1 + phase * 3.7) * 0.09;
  let downSlope = sin(uvX * 12.0 + uvY * 7.0 - time * 5.4 + phase * 6.2831853) * 0.055;
  return normalize(vec3f(-crossSlope, downSlope, 1.0));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let kind = floor(bm_in.aFeature.x + 0.5);
  var world = bm_in.aPosition;
  var normal = bm_in.aNormal;
  var signal = 0.0;
  if (kind < 0.5) {
    signal = sin(bm_in.aPosition.x * 2.1 + bm_u.uTime * 0.85) * 0.56 + sin(bm_in.aPosition.z * 1.7 - bm_u.uTime * 0.72) * 0.3 + sin((bm_in.aPosition.x + bm_in.aPosition.z) * 3.2 + bm_u.uTime * 1.13) * 0.14;
    world = vec3f(bm_in.aPosition.x, bm_in.aPosition.y + signal * bm_in.aFeature.z, bm_in.aPosition.z);
    normal = surfaceNormal(world, bm_u.uTime, bm_in.aFeature.z);
  } else {
    if (kind < 1.5) {
      let sidePin = smoothstep(0.0, 0.1, bm_in.aUv.x) * smoothstep(0.0, 0.1, 1.0 - bm_in.aUv.x);
      let topPin = smoothstep(0.0, 0.065, bm_in.aUv.y);
      signal = sin(bm_in.aUv.x * 12.0 + bm_in.aUv.y * 7.0 - bm_u.uTime * 5.4 + bm_in.aFeature.y * 6.2831853) * 0.62 + sin(bm_in.aUv.x * 29.0 - bm_in.aUv.y * 4.0 - bm_u.uTime * 8.1 + bm_in.aFeature.y * 3.7) * 0.38;
      let pinnedSignal = signal * sidePin * topPin;
      world = vec3f(bm_in.aPosition.x + sin(bm_in.aUv.y * 18.0 - bm_u.uTime * 4.7 + bm_in.aFeature.y) * bm_in.aFeature.z * 0.16 * sidePin * topPin, bm_in.aPosition.y, bm_in.aPosition.z + pinnedSignal * bm_in.aFeature.z);
      normal = fallingNormal(bm_in.aUv.x, bm_in.aUv.y, bm_in.aFeature.y, bm_u.uTime);
    } else {
      let endpointPin = smoothstep(0.0, 0.1, bm_in.aUv.y) * smoothstep(0.0, 0.13, 1.0 - bm_in.aUv.y);
      signal = sin(bm_in.aUv.y * 46.0 - bm_u.uTime * 9.2 + bm_in.aFeature.y * 6.2831853) * 0.7 + sin(bm_in.aUv.y * 19.0 - bm_u.uTime * 5.1 + bm_in.aUv.x * 6.2831853) * 0.3;
      world = bm_in.aPosition + bm_in.aNormal * (signal * bm_in.aFeature.z * endpointPin);
      normal = normalize(bm_in.aNormal + vec3f(cos(bm_in.aUv.y * 19.0 - bm_u.uTime * 5.1) * 0.035, sin(bm_in.aUv.y * 31.0 - bm_u.uTime * 7.3 + bm_in.aFeature.y) * 0.025, cos(bm_in.aUv.y * 23.0 - bm_u.uTime * 6.4 + bm_in.aFeature.y) * 0.035));
    }
  }
  bm_out.vWorld = world;
  bm_out.vNormal = normal;
  bm_out.vUv = bm_in.aUv;
  bm_out.vFeature = bm_in.aFeature;
  bm_out.vSignal = signal;
  bm_out.vDepth = length(world - bm_u.uCamPos);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let kind = floor(bm_in.vFeature.x + 0.5);
  let baseNormal = normalize(bm_in.vNormal);
  let detailRate = 0.55;
  let detailStrength = 0.3;
  let weightX = abs(baseNormal.x);
  let weightY = abs(baseNormal.y);
  let weightZ = abs(baseNormal.z);
  let weightSum = weightX + weightY + weightZ;
  let detailX = textureSample(uDetailNormal, uDetailNormal_sampler, vec2f(bm_in.vWorld.z, bm_in.vWorld.y) * detailRate).xyz;
  let detailY = textureSample(uDetailNormal, uDetailNormal_sampler, bm_in.vWorld.xz * detailRate).xyz;
  let detailZ = textureSample(uDetailNormal, uDetailNormal_sampler, bm_in.vWorld.xy * detailRate).xyz;
  let tiltX = detailX * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tiltY = detailY * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tiltZ = detailZ * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tilt = (vec3f(0.0, tiltX.y, tiltX.x) * weightX + vec3f(tiltY.x, 0.0, tiltY.y) * weightY + vec3f(tiltZ.x, tiltZ.y, 0.0) * weightZ) * (detailStrength / weightSum);
  let normal = normalize(baseNormal + tilt);
  let view = normalize(bm_u.uCamPos - bm_in.vWorld);
  let light = normalize(bm_u.uLightDir);
  let ndotl = max(dot(normal, light), 0.0);
  let lightClip = bm_u.uLightViewProj * vec4f(bm_in.vWorld, 1.0);
  let shadowUv = ((lightClip).xy / (lightClip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let receiverDepth = clamp(lightClip.z / lightClip.w * 0.5 + 0.5, 0.0, 1.0);
  let insideShadow = step(0.001, shadowUv.x) * step(shadowUv.x, 0.999) * step(0.001, shadowUv.y) * step(shadowUv.y, 0.999) * step(0.001, receiverDepth) * step(receiverDepth, 0.999) * step(0.001, lightClip.w);
  let depthBias = bm_u.uShadowBias * (1.0 + (1.0 - ndotl) * 1.8);
  var occluded = 0.0;
  for (var i = 0.0; i < 4.0; i = i + 1.0) {
    let x = ((i) - (2.0) * floor((i) / (2.0))) - 0.5;
    let y = floor(i / 2.0) - 0.5;
    let stored = textureSample(uShadowMap, uShadowMap_sampler, shadowUv + bm_u.uShadowTexel * vec2f(x, y));
    let nearestDepth = stored.x + stored.y / 255.0;
    occluded = occluded + step(nearestDepth + depthBias, receiverDepth);
  }
  let shadow = 1.0 - insideShadow * clamp(bm_u.uShadowStrength, 0.0, 1.0) * occluded * 0.25;
  var color = bm_u.uDeepColor;
  var foam = 0.0;
  var reflectionStrength = 0.68;
  var roughness = clamp(bm_u.uRoughness, 0.08, 1.0);
  if (kind < 0.5) {
    let centeredUv = (bm_in.vUv - vec2f(0.5)) * 2.0;
    let radial = length(centeredUv);
    let ring = sin(radial * 31.0 - bm_u.uTime * 5.2 + bm_in.vFeature.y * 6.2831853) * 0.5 + 0.5;
    let crossing = sin((bm_in.vWorld.x - bm_in.vWorld.z) * 4.3 + bm_u.uTime * 1.7) * 0.5 + 0.5;
    let bodyMix = 0.2 + smoothstep(-0.85, 0.9, bm_in.vSignal) * 0.2;
    color = mix(bm_u.uDeepColor, bm_u.uShallowColor, bodyMix);
    let rim = smoothstep(0.82, 1.02, radial) * (0.08 + bm_in.vFeature.w * 0.22);
    foam = clamp(rim + bm_in.vFeature.w * smoothstep(0.58, 0.92, ring) * (0.45 + crossing * 0.55), 0.0, 1.0);
    if (bm_in.vFeature.w > 0.8) {
      let brokenSplash = max(ring, crossing * 0.82);
      if (brokenSplash < 0.42) {
        discard;
      }
    }
  } else {
    if (kind < 1.5) {
      let streakA = sin(bm_in.vUv.x * 43.0 + bm_in.vUv.y * 13.0 - bm_u.uTime * 8.6 + bm_in.vFeature.y * 4.1) * 0.5 + 0.5;
      let streakB = sin(bm_in.vUv.x * 17.0 - bm_in.vUv.y * 31.0 - bm_u.uTime * 12.1 + bm_in.vFeature.y * 6.7) * 0.5 + 0.5;
      let braided = streakA * 0.62 + streakB * 0.38;
      let edge = smoothstep(0.68, 0.98, abs(bm_in.vUv.x * 2.0 - 1.0));
      let plunge = smoothstep(0.68, 1.0, bm_in.vUv.y);
      foam = clamp(edge * (0.42 + braided * 0.38) + plunge * (0.28 + streakB * 0.5) + smoothstep(0.7, 0.96, braided) * (0.16 + bm_in.vFeature.w * 0.5), 0.0, 1.0);
      if (bm_in.vFeature.w > 0.2) {
        let veil = max(foam, smoothstep(0.64, 0.94, braided) * (0.62 + bm_in.vFeature.w * 0.38));
        if (veil < 0.46 + bm_in.vFeature.w * 0.08) {
          discard;
        }
      }
      color = mix(bm_u.uDeepColor, bm_u.uShallowColor, 0.52 + braided * 0.28);
      reflectionStrength = 0.38;
      roughness = clamp(roughness + 0.14, 0.08, 1.0);
    } else {
      let streamBand = sin(bm_in.vUv.y * 73.0 - bm_u.uTime * 13.4 + bm_in.vFeature.y * 6.2831853) * 0.5 + 0.5;
      let around = sin(bm_in.vUv.x * 12.5663706 + bm_in.vUv.y * 19.0 - bm_u.uTime * 5.8) * 0.5 + 0.5;
      foam = 0.46 + smoothstep(0.52, 0.94, streamBand) * 0.38 + around * 0.1;
      color = mix(bm_u.uShallowColor, bm_u.uFoamColor, 0.42 + streamBand * 0.26);
      reflectionStrength = 0.3;
      roughness = clamp(roughness + 0.2, 0.08, 1.0);
    }
  }
  let ndotv = max(dot(normal, view), 0.0);
  let fresnel = 0.025 + 0.975 * pow(1.0 - ndotv, 5.0);
  color = mix(color, bm_u.uSkyColor, fresnel * reflectionStrength);
  color = mix(color, bm_u.uFoamColor, clamp(foam, 0.0, 1.0) * 0.82);
  let sunSpecular = min(specGGX(normal, light, view, roughness), 3.0) * bm_u.uSunIntensity * shadow;
  let directional = (0.14 + ndotl * 0.22) * shadow;
  color = color * (0.72 + directional) + bm_u.uSunColor * (sunSpecular + ndotl * shadow * 0.035);
  let fog = smoothstep(bm_u.uFogStart, bm_u.uFogEnd, bm_in.vDepth) * clamp(bm_u.uFogStrength, 0.0, 1.0);
  color = mix(color, bm_u.uFogColor, fog);
  return vec4f(vec3f(max(color.x, 0.0), max(color.y, 0.0), max(color.z, 0.0)), bm_in.vDepth);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aUv: 'vec2', aFeature: 'vec4' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uLightViewProj: 'mat4', uCamPos: 'vec3', uLightDir: 'vec3', uSunColor: 'vec3', uSunIntensity: 'float', uSkyColor: 'vec3', uDeepColor: 'vec3', uShallowColor: 'vec3', uFoamColor: 'vec3', uRoughness: 'float', uTime: 'float', uFogColor: 'vec3', uFogStart: 'float', uFogEnd: 'float', uFogStrength: 'float', uShadowMap: 'sampler2D', uDetailNormal: 'sampler2D', uShadowTexel: 'vec2', uShadowBias: 'float', uShadowStrength: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0},{"name":"aFeature","type":"vec4","location":3,"size":4,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uSunColor","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uSunIntensity","type":"float","kind":"1f","size":1,"offset":172},{"name":"uSkyColor","type":"vec3","kind":"3fv","size":3,"offset":176},{"name":"uDeepColor","type":"vec3","kind":"3fv","size":3,"offset":192},{"name":"uShallowColor","type":"vec3","kind":"3fv","size":3,"offset":208},{"name":"uFoamColor","type":"vec3","kind":"3fv","size":3,"offset":224},{"name":"uRoughness","type":"float","kind":"1f","size":1,"offset":236},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":240},{"name":"uFogColor","type":"vec3","kind":"3fv","size":3,"offset":256},{"name":"uFogStart","type":"float","kind":"1f","size":1,"offset":268},{"name":"uFogEnd","type":"float","kind":"1f","size":1,"offset":272},{"name":"uFogStrength","type":"float","kind":"1f","size":1,"offset":276},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uDetailNormal","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uShadowTexel","type":"vec2","kind":"2fv","size":2,"offset":280},{"name":"uShadowBias","type":"float","kind":"1f","size":1,"offset":288},{"name":"uShadowStrength","type":"float","kind":"1f","size":1,"offset":292}],"uniformBlockSize":304},

};

export default townWaterFeaturesShader;
