/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const groundShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uModel: 'mat4'; uFog: 'vec3'; uCamPos: 'vec3'; uFogDist: 'float'; uBase: 'vec3'; uLine: 'vec3' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uFog : vec3f,
  uCamPos : vec3f,
  uFogDist : f32,
  uBase : vec3f,
  uLine : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = bm_u.uModel * vec4f(bm_in.aPosition, 1.0);
  bm_out.vWorld = world.xyz;
  bm_out.bm_position = bm_u.uViewProj * world;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let gx = abs(fract(bm_in.vWorld.x) - 0.5);
  let gz = abs(fract(bm_in.vWorld.z) - 0.5);
  let grid = smoothstep(0.44, 0.5, max(gx, gz));
  let fog = clamp(length(bm_in.vWorld - bm_u.uCamPos) / bm_u.uFogDist, 0.0, 1.0);
  return vec4f(mix(mix(bm_u.uBase, bm_u.uLine, grid * 0.7), bm_u.uFog, fog * 0.95), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uFog: 'vec3', uCamPos: 'vec3', uFogDist: 'float', uBase: 'vec3', uLine: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uFog","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uFogDist","type":"float","kind":"1f","size":1,"offset":156},{"name":"uBase","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uLine","type":"vec3","kind":"3fv","size":3,"offset":176}],"uniformBlockSize":192},

};

export default groundShader;
