/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const stormShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iSeed: 'vec4' }, { uViewProj: 'mat4'; uTime: 'float'; uSpread: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
  uSpread : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iSeed : vec4f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vColor : vec3f,
  @location(1) vNormal : vec3f,
}
fn cosinePalette(t : f32, a : vec3f, b : vec3f, c : vec3f, d : vec3f) -> vec3f {
  let phase = (c * t + d) * 6.28318;
  return a + vec3f(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
fn rotate3(p : vec3f, axis : vec3f, angle : f32) -> vec3f {
  let a = normalize(axis);
  let c = cos(angle);
  let s = sin(angle);
  return p * c + cross(a, p) * s + a * (dot(a, p) * (1.0 - c));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let orbit = bm_in.iSeed.x * 6.2831853 + bm_u.uTime * (0.08 + bm_in.iSeed.y * 0.22);
  let radius = (0.25 + bm_in.iSeed.z * 0.75) * bm_u.uSpread;
  let rise = sin(bm_u.uTime * (0.2 + bm_in.iSeed.w * 0.5) + bm_in.iSeed.x * 9.0) * bm_u.uSpread * 0.32;
  let centre = vec3f(cos(orbit) * radius, rise + (bm_in.iSeed.w - 0.5) * bm_u.uSpread * 0.5, sin(orbit) * radius);
  let axis = vec3f(bm_in.iSeed.y - 0.5, bm_in.iSeed.z + 0.2, bm_in.iSeed.x - 0.5);
  let spun = rotate3(bm_in.aPosition * (0.06 + bm_in.iSeed.z * 0.05), axis, bm_u.uTime * (0.6 + bm_in.iSeed.y * 2.0));
  bm_out.vNormal = rotate3(bm_in.aNormal, axis, bm_u.uTime * (0.6 + bm_in.iSeed.y * 2.0));
  bm_out.vColor = cosinePalette(fract(bm_in.iSeed.x * 0.7 + bm_in.iSeed.z * 0.3), vec3f(0.42, 0.3, 0.28), vec3f(0.45, 0.32, 0.3), vec3f(1.0, 0.9, 0.7), vec3f(0.0, 0.15, 0.35));
  bm_out.bm_position = bm_u.uViewProj * vec4f(spun + centre, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let key = lambert(bm_in.vNormal, vec3f(0.4, 0.8, 0.45));
  return vec4f(bm_in.vColor * (0.3 + key * 0.9), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iSeed: 'vec4' },
  uniforms: { uViewProj: 'mat4', uTime: 'float', uSpread: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iSeed","type":"vec4","location":2,"size":4,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uSpread","type":"float","kind":"1f","size":1,"offset":68}],"uniformBlockSize":80},

};

export default stormShader;
