/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const townVoxelShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aBaseColor: 'vec3'; aMaterial: 'vec2'; aLocalAo: 'float'; aEmissive: 'float' }, Record<string, never>, { uViewProj: 'mat4'; uLightViewProj: 'mat4'; uCamPos: 'vec3'; uLightDir: 'vec3'; uSunColor: 'vec3'; uSunIntensity: 'float'; uSkyColor: 'vec3'; uSkyIntensity: 'float'; uGroundColor: 'vec3'; uGroundIntensity: 'float'; uEmissiveIntensity: 'float'; uFogColor: 'vec3'; uFogStart: 'float'; uFogEnd: 'float'; uFogStrength: 'float'; uShadowMap: 'sampler2D'; uShadowTexel: 'vec2'; uShadowBias: 'float'; uShadowSlopeBias: 'float'; uShadowStrength: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in vec3 aBaseColor;
layout(location = 3) in vec2 aMaterial;
layout(location = 4) in float aLocalAo;
layout(location = 5) in float aEmissive;
uniform mat4 uViewProj;
uniform vec3 uCamPos;
out vec3 vWorld;
out vec3 vNormal;
out vec3 vBaseColor;
out vec2 vMaterial;
out float vLocalAo;
out float vEmissive;
out float vDepth;
void main() {
  vWorld = aPosition;
  vNormal = aNormal;
  vBaseColor = aBaseColor;
  vMaterial = aMaterial;
  vLocalAo = aLocalAo;
  vEmissive = aEmissive;
  vDepth = length(aPosition - uCamPos);
  gl_Position = uViewProj * vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform mat4 uLightViewProj;
uniform vec3 uCamPos;
uniform vec3 uLightDir;
uniform vec3 uSunColor;
uniform float uSunIntensity;
uniform vec3 uSkyColor;
uniform float uSkyIntensity;
uniform vec3 uGroundColor;
uniform float uGroundIntensity;
uniform float uEmissiveIntensity;
uniform vec3 uFogColor;
uniform float uFogStart;
uniform float uFogEnd;
uniform float uFogStrength;
uniform sampler2D uShadowMap;
uniform vec2 uShadowTexel;
uniform float uShadowBias;
uniform float uShadowSlopeBias;
uniform float uShadowStrength;
in vec3 vWorld;
in vec3 vNormal;
in vec3 vBaseColor;
in vec2 vMaterial;
in float vLocalAo;
in float vEmissive;
in float vDepth;
out vec4 fragColor;
float specGGX(vec3 normal, vec3 lightDir, vec3 viewDir, float roughness) {
  vec3 n = normalize(normal);
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  float ndoth = max(dot(n, halfway), 0.0);
  float a = roughness * roughness;
  float a2 = a * a;
  float denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  float ndf = a2 / (3.14159265 * denom * denom);
  float ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
void main() {
  vec3 normal = normalize(vNormal);
  vec3 light = normalize(uLightDir);
  vec3 view = normalize(uCamPos - vWorld);
  float ndotl = max(dot(normal, light), 0.0);
  vec4 lightClip = uLightViewProj * vec4(vWorld, 1.0);
  vec2 shadowUv = ((lightClip).xy / (lightClip).w * 0.5 + 0.5);
  float receiverDepth = clamp(lightClip.z / lightClip.w * 0.5 + 0.5, 0.0, 1.0);
  float insideShadow = step(0.001, shadowUv.x) * step(shadowUv.x, 0.999) * step(0.001, shadowUv.y) * step(shadowUv.y, 0.999) * step(0.001, receiverDepth) * step(receiverDepth, 0.999) * step(0.001, lightClip.w);
  float slope = 1.0 - ndotl;
  float depthBias = uShadowBias + uShadowSlopeBias * slope * slope;
  float occluded = 0.0;
  for (float i = 0.0; i < 9.0; i = i + 1.0) {
    float x = mod(i, 3.0) - 1.0;
    float y = floor(i / 3.0) - 1.0;
    vec4 stored = texture(uShadowMap, shadowUv + uShadowTexel * vec2(x, y));
    float nearestDepth = stored.x + stored.y / 255.0;
    occluded = occluded + step(nearestDepth + depthBias, receiverDepth);
  }
  float shadow = 1.0 - insideShadow * clamp(uShadowStrength, 0.0, 1.0) * occluded / 9.0;
  float ao = clamp(vLocalAo, 0.0, 1.0);
  float cavity = 1.0 - ao;
  float roughness = clamp(vMaterial.x, 0.12, 1.0);
  float specularLevel = clamp(vMaterial.y, 0.0, 1.0);
  float up = normal.y * 0.5 + 0.5;
  vec3 sky = uSkyColor * (uSkyIntensity * (0.28 + up * 0.72));
  vec3 ground = uGroundColor * (uGroundIntensity * (0.22 + (1.0 - up) * 0.78));
  float ambientVisibility = 0.62 + ao * 0.38;
  vec3 indirect = (sky + ground + vec3(0.055, 0.068, 0.1)) * (ambientVisibility * 0.6);
  float directVisibility = 1.0 - cavity * (0.16 + roughness * 0.08);
  vec3 warmKey = mix(vec3(1.0, 0.94, 0.84), uSunColor, 0.48);
  float keyShadow = shadow * shadow;
  vec3 direct = warmKey * (uSunIntensity * 0.55 * ndotl * keyShadow * directVisibility);
  float diffuseEnergy = 1.0 - specularLevel * 0.22;
  vec3 color = vBaseColor * diffuseEnergy * (indirect + direct);
  vec3 cavityTint = mix(vec3(0.78, 0.86, 1.0), vec3(1.0, 1.0, 1.0), ao);
  color = color * cavityTint;
  float sunSpecular = min(specGGX(normal, light, view, roughness), 1.8) * specularLevel * uSunIntensity * 0.55 * keyShadow * (1.0 - cavity * 0.28);
  float ndotv = max(dot(normal, view), 0.0);
  float fresnel = pow(1.0 - ndotv, 5.0);
  float smoothness = 1.0 - roughness;
  float edgeReflectance = (0.035 + specularLevel * 0.28) * (0.28 + smoothness * 0.72);
  float edgeSheen = fresnel * edgeReflectance * (0.72 + ao * 0.28);
  vec3 environment = mix(uGroundColor, uSkyColor, up);
  float roughBackscatter = pow(1.0 - ndotv, 3.0) * roughness * ndotl * keyShadow * 0.035;
  color = color + warmKey * sunSpecular + environment * edgeSheen + vBaseColor * warmKey * roughBackscatter;
  float emissiveStrength = max(vEmissive, 0.0) * uEmissiveIntensity;
  color = color + vBaseColor * emissiveStrength + uSunColor * (emissiveStrength * 0.12);
  float fog = smoothstep(uFogStart, uFogEnd, vDepth) * clamp(uFogStrength, 0.0, 1.0);
  color = mix(color, uFogColor, fog);
  fragColor = vec4(max(color, vec3(0.0, 0.0, 0.0)), vDepth);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uLightViewProj : mat4x4f,
  uCamPos : vec3f,
  uLightDir : vec3f,
  uSunColor : vec3f,
  uSunIntensity : f32,
  uSkyColor : vec3f,
  uSkyIntensity : f32,
  uGroundColor : vec3f,
  uGroundIntensity : f32,
  uEmissiveIntensity : f32,
  uFogColor : vec3f,
  uFogStart : f32,
  uFogEnd : f32,
  uFogStrength : f32,
  uShadowTexel : vec2f,
  uShadowBias : f32,
  uShadowSlopeBias : f32,
  uShadowStrength : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uShadowMap : texture_2d<f32>;
@group(0) @binding(2) var uShadowMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aBaseColor : vec3f,
  @location(3) aMaterial : vec2f,
  @location(4) aLocalAo : f32,
  @location(5) aEmissive : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vBaseColor : vec3f,
  @location(3) vMaterial : vec2f,
  @location(4) vLocalAo : f32,
  @location(5) vEmissive : f32,
  @location(6) vDepth : f32,
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vWorld = bm_in.aPosition;
  bm_out.vNormal = bm_in.aNormal;
  bm_out.vBaseColor = bm_in.aBaseColor;
  bm_out.vMaterial = bm_in.aMaterial;
  bm_out.vLocalAo = bm_in.aLocalAo;
  bm_out.vEmissive = bm_in.aEmissive;
  bm_out.vDepth = length(bm_in.aPosition - bm_u.uCamPos);
  bm_out.bm_position = bm_u.uViewProj * vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = normalize(bm_in.vNormal);
  let light = normalize(bm_u.uLightDir);
  let view = normalize(bm_u.uCamPos - bm_in.vWorld);
  let ndotl = max(dot(normal, light), 0.0);
  let lightClip = bm_u.uLightViewProj * vec4f(bm_in.vWorld, 1.0);
  let shadowUv = ((lightClip).xy / (lightClip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let receiverDepth = clamp(lightClip.z / lightClip.w * 0.5 + 0.5, 0.0, 1.0);
  let insideShadow = step(0.001, shadowUv.x) * step(shadowUv.x, 0.999) * step(0.001, shadowUv.y) * step(shadowUv.y, 0.999) * step(0.001, receiverDepth) * step(receiverDepth, 0.999) * step(0.001, lightClip.w);
  let slope = 1.0 - ndotl;
  let depthBias = bm_u.uShadowBias + bm_u.uShadowSlopeBias * slope * slope;
  var occluded = 0.0;
  for (var i = 0.0; i < 9.0; i = i + 1.0) {
    let x = ((i) - (3.0) * floor((i) / (3.0))) - 1.0;
    let y = floor(i / 3.0) - 1.0;
    let stored = textureSample(uShadowMap, uShadowMap_sampler, shadowUv + bm_u.uShadowTexel * vec2f(x, y));
    let nearestDepth = stored.x + stored.y / 255.0;
    occluded = occluded + step(nearestDepth + depthBias, receiverDepth);
  }
  let shadow = 1.0 - insideShadow * clamp(bm_u.uShadowStrength, 0.0, 1.0) * occluded / 9.0;
  let ao = clamp(bm_in.vLocalAo, 0.0, 1.0);
  let cavity = 1.0 - ao;
  let roughness = clamp(bm_in.vMaterial.x, 0.12, 1.0);
  let specularLevel = clamp(bm_in.vMaterial.y, 0.0, 1.0);
  let up = normal.y * 0.5 + 0.5;
  let sky = bm_u.uSkyColor * (bm_u.uSkyIntensity * (0.28 + up * 0.72));
  let ground = bm_u.uGroundColor * (bm_u.uGroundIntensity * (0.22 + (1.0 - up) * 0.78));
  let ambientVisibility = 0.62 + ao * 0.38;
  let indirect = (sky + ground + vec3f(0.055, 0.068, 0.1)) * (ambientVisibility * 0.6);
  let directVisibility = 1.0 - cavity * (0.16 + roughness * 0.08);
  let warmKey = mix(vec3f(1.0, 0.94, 0.84), bm_u.uSunColor, 0.48);
  let keyShadow = shadow * shadow;
  let direct = warmKey * (bm_u.uSunIntensity * 0.55 * ndotl * keyShadow * directVisibility);
  let diffuseEnergy = 1.0 - specularLevel * 0.22;
  var color = bm_in.vBaseColor * diffuseEnergy * (indirect + direct);
  let cavityTint = mix(vec3f(0.78, 0.86, 1.0), vec3f(1.0, 1.0, 1.0), ao);
  color = color * cavityTint;
  let sunSpecular = min(specGGX(normal, light, view, roughness), 1.8) * specularLevel * bm_u.uSunIntensity * 0.55 * keyShadow * (1.0 - cavity * 0.28);
  let ndotv = max(dot(normal, view), 0.0);
  let fresnel = pow(1.0 - ndotv, 5.0);
  let smoothness = 1.0 - roughness;
  let edgeReflectance = (0.035 + specularLevel * 0.28) * (0.28 + smoothness * 0.72);
  let edgeSheen = fresnel * edgeReflectance * (0.72 + ao * 0.28);
  let environment = mix(bm_u.uGroundColor, bm_u.uSkyColor, up);
  let roughBackscatter = pow(1.0 - ndotv, 3.0) * roughness * ndotl * keyShadow * 0.035;
  color = color + warmKey * sunSpecular + environment * edgeSheen + bm_in.vBaseColor * warmKey * roughBackscatter;
  let emissiveStrength = max(bm_in.vEmissive, 0.0) * bm_u.uEmissiveIntensity;
  color = color + bm_in.vBaseColor * emissiveStrength + bm_u.uSunColor * (emissiveStrength * 0.12);
  let fog = smoothstep(bm_u.uFogStart, bm_u.uFogEnd, bm_in.vDepth) * clamp(bm_u.uFogStrength, 0.0, 1.0);
  color = mix(color, bm_u.uFogColor, fog);
  return vec4f(max(color, vec3f(0.0, 0.0, 0.0)), bm_in.vDepth);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aBaseColor: 'vec3', aMaterial: 'vec2', aLocalAo: 'float', aEmissive: 'float' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uLightViewProj: 'mat4', uCamPos: 'vec3', uLightDir: 'vec3', uSunColor: 'vec3', uSunIntensity: 'float', uSkyColor: 'vec3', uSkyIntensity: 'float', uGroundColor: 'vec3', uGroundIntensity: 'float', uEmissiveIntensity: 'float', uFogColor: 'vec3', uFogStart: 'float', uFogEnd: 'float', uFogStrength: 'float', uShadowMap: 'sampler2D', uShadowTexel: 'vec2', uShadowBias: 'float', uShadowSlopeBias: 'float', uShadowStrength: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aBaseColor","type":"vec3","location":2,"size":3,"divisor":0},{"name":"aMaterial","type":"vec2","location":3,"size":2,"divisor":0},{"name":"aLocalAo","type":"float","location":4,"size":1,"divisor":0},{"name":"aEmissive","type":"float","location":5,"size":1,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uSunColor","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uSunIntensity","type":"float","kind":"1f","size":1,"offset":172},{"name":"uSkyColor","type":"vec3","kind":"3fv","size":3,"offset":176},{"name":"uSkyIntensity","type":"float","kind":"1f","size":1,"offset":188},{"name":"uGroundColor","type":"vec3","kind":"3fv","size":3,"offset":192},{"name":"uGroundIntensity","type":"float","kind":"1f","size":1,"offset":204},{"name":"uEmissiveIntensity","type":"float","kind":"1f","size":1,"offset":208},{"name":"uFogColor","type":"vec3","kind":"3fv","size":3,"offset":224},{"name":"uFogStart","type":"float","kind":"1f","size":1,"offset":236},{"name":"uFogEnd","type":"float","kind":"1f","size":1,"offset":240},{"name":"uFogStrength","type":"float","kind":"1f","size":1,"offset":244},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uShadowTexel","type":"vec2","kind":"2fv","size":2,"offset":248},{"name":"uShadowBias","type":"float","kind":"1f","size":1,"offset":256},{"name":"uShadowSlopeBias","type":"float","kind":"1f","size":1,"offset":260},{"name":"uShadowStrength","type":"float","kind":"1f","size":1,"offset":264}],"uniformBlockSize":272},
};

export default townVoxelShader;
