/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const townFoliageShadowShader: CompiledShader<{ aPosition: 'vec3'; aNormalWind: 'vec4'; aUv: 'vec2' }, { iCenter: 'vec3'; iShape: 'vec4'; iUvRect: 'vec4'; iTint: 'vec3'; iWindKind: 'vec3' }, { uLightViewProj: 'mat4'; uAtlas: 'sampler2D'; uCutoff: 'float'; uTime: 'float'; uWindDirection: 'vec2'; uWindStrength: 'float'; uWindSpeed: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location=0)in vec3 aPosition;layout(location=1)in vec4 aNormalWind;layout(location=2)in vec2 aUv;layout(location=3)in vec3 iCenter;layout(location=4)in vec4 iShape;layout(location=5)in vec4 iUvRect;layout(location=6)in vec3 iTint;layout(location=7)in vec3 iWindKind;uniform mat4 uLightViewProj;uniform float uTime;uniform vec2 uWindDirection;uniform float uWindStrength;uniform float uWindSpeed;out vec2 vUv;out float vKind;out vec3 vWorld;void main(){float aWindWeight=aNormalWind.w;vec2 iWind=iWindKind.xy;float iKind=iWindKind.z;float width=max(iShape.x,0.001);float height=max(iShape.y,0.001);float cosine=cos(iShape.z);float sine=sin(iShape.z);vec3 local=vec3(aPosition.x*width,aPosition.y*height,aPosition.z*width);vec3 rotated=vec3(local.x*cosine - local.z*sine,local.y,local.x*sine + local.z*cosine);float windLength=max(length(uWindDirection),0.001);vec2 windDirection=uWindDirection*(1.0/windLength);float anchorWeight=mix(1.0 - clamp(aWindWeight,0.0,1.0),clamp(aWindWeight,0.0,1.0),clamp(iWind.y,0.0,1.0));float phase=iShape.w*6.2831853 + iCenter.x*0.19 + iCenter.z*0.27;float primary=sin(uTime*uWindSpeed + phase + aWindWeight*0.8);float flutter=sin(uTime*uWindSpeed*2.73 + phase*1.71)*0.34;float sway=(primary + flutter)*iWind.x*uWindStrength*anchorWeight*anchorWeight;vec3 world=iCenter + rotated + vec3(windDirection.x*sway,0.0,windDirection.y*sway);float interfaceNoop=aNormalWind.x*0.0 + iTint.x*0.0;vUv=iUvRect.xy + aUv*iUvRect.zw + vec3(interfaceNoop,interfaceNoop,0.0).xy;vKind=iKind;vWorld=world;gl_Position=uLightViewProj*vec4(world,1.0);}
`,
  fragmentSrc: `#version 300 es
precision highp float;uniform mat4 uLightViewProj;uniform sampler2D uAtlas;uniform float uCutoff;in vec2 vUv;in float vKind;in vec3 vWorld;out vec4 fragColor;void main(){vec4 atlasSample=texture(uAtlas,vUv);if(vKind<0.5){if(atlasSample.w<uCutoff){discard;}}vec4 clip=uLightViewProj*vec4(vWorld,1.0);float depth=clamp(clip.z/clip.w*0.5 + 0.5,0.0,1.0);float scaled=depth*255.0;float high=floor(scaled)/255.0;float low=fract(scaled);fragColor=vec4(high,low,depth,1.0);}
`,
  wgslSrc: `struct BmUniforms {
  uLightViewProj : mat4x4f,
  uCutoff : f32,
  uTime : f32,
  uWindDirection : vec2f,
  uWindStrength : f32,
  uWindSpeed : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormalWind : vec4f,
  @location(2) aUv : vec2f,
  @location(3) iCenter : vec3f,
  @location(4) iShape : vec4f,
  @location(5) iUvRect : vec4f,
  @location(6) iTint : vec3f,
  @location(7) iWindKind : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vKind : f32,
  @location(2) vWorld : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let aWindWeight = bm_in.aNormalWind.w;
  let iWind = bm_in.iWindKind.xy;
  let iKind = bm_in.iWindKind.z;
  let width = max(bm_in.iShape.x, 0.001);
  let height = max(bm_in.iShape.y, 0.001);
  let cosine = cos(bm_in.iShape.z);
  let sine = sin(bm_in.iShape.z);
  let local = vec3f(bm_in.aPosition.x * width, bm_in.aPosition.y * height, bm_in.aPosition.z * width);
  let rotated = vec3f(local.x * cosine - local.z * sine, local.y, local.x * sine + local.z * cosine);
  let windLength = max(length(bm_u.uWindDirection), 0.001);
  let windDirection = bm_u.uWindDirection * (1.0 / windLength);
  let anchorWeight = mix(1.0 - clamp(aWindWeight, 0.0, 1.0), clamp(aWindWeight, 0.0, 1.0), clamp(iWind.y, 0.0, 1.0));
  let phase = bm_in.iShape.w * 6.2831853 + bm_in.iCenter.x * 0.19 + bm_in.iCenter.z * 0.27;
  let primary = sin(bm_u.uTime * bm_u.uWindSpeed + phase + aWindWeight * 0.8);
  let flutter = sin(bm_u.uTime * bm_u.uWindSpeed * 2.73 + phase * 1.71) * 0.34;
  let sway = (primary + flutter) * iWind.x * bm_u.uWindStrength * anchorWeight * anchorWeight;
  let world = bm_in.iCenter + rotated + vec3f(windDirection.x * sway, 0.0, windDirection.y * sway);
  let interfaceNoop = bm_in.aNormalWind.x * 0.0 + bm_in.iTint.x * 0.0;
  bm_out.vUv = bm_in.iUvRect.xy + bm_in.aUv * bm_in.iUvRect.zw + vec3f(interfaceNoop, interfaceNoop, 0.0).xy;
  bm_out.vKind = iKind;
  bm_out.vWorld = world;
  bm_out.bm_position = bm_u.uLightViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let atlasSample = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  if (bm_in.vKind < 0.5) {
    if (atlasSample.w < bm_u.uCutoff) {
      discard;
    }
  }
  let clip = bm_u.uLightViewProj * vec4f(bm_in.vWorld, 1.0);
  let depth = clamp(clip.z / clip.w * 0.5 + 0.5, 0.0, 1.0);
  let scaled = depth * 255.0;
  let high = floor(scaled) / 255.0;
  let low = fract(scaled);
  return vec4f(high, low, depth, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormalWind: 'vec4', aUv: 'vec2' },
  instanceAttributes: { iCenter: 'vec3', iShape: 'vec4', iUvRect: 'vec4', iTint: 'vec3', iWindKind: 'vec3' },
  uniforms: { uLightViewProj: 'mat4', uAtlas: 'sampler2D', uCutoff: 'float', uTime: 'float', uWindDirection: 'vec2', uWindStrength: 'float', uWindSpeed: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormalWind","type":"vec4","location":1,"size":4,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0},{"name":"iCenter","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iShape","type":"vec4","location":4,"size":4,"divisor":1},{"name":"iUvRect","type":"vec4","location":5,"size":4,"divisor":1},{"name":"iTint","type":"vec3","location":6,"size":3,"divisor":1},{"name":"iWindKind","type":"vec3","location":7,"size":3,"divisor":1}],"uniforms":[{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":68},{"name":"uWindDirection","type":"vec2","kind":"2fv","size":2,"offset":72},{"name":"uWindStrength","type":"float","kind":"1f","size":1,"offset":80},{"name":"uWindSpeed","type":"float","kind":"1f","size":1,"offset":84}],"uniformBlockSize":96},
};

export default townFoliageShadowShader;
