/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const townWaterShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uLightViewProj: 'mat4'; uCamPos: 'vec3'; uLightDir: 'vec3'; uSunColor: 'vec3'; uSunIntensity: 'float'; uSkyColor: 'vec3'; uDeepColor: 'vec3'; uShallowColor: 'vec3'; uRoughness: 'float'; uCrestStrength: 'float'; uFogColor: 'vec3'; uFogStart: 'float'; uFogEnd: 'float'; uFogStrength: 'float'; uTime: 'float'; uWaterLevel: 'float'; uShadowMap: 'sampler2D'; uShadowTexel: 'vec2'; uShadowBias: 'float'; uShadowStrength: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
uniform mat4 uViewProj;
uniform vec3 uCamPos;
uniform float uTime;
uniform float uWaterLevel;
out vec3 vWorld;
out float vDepth;
out float vRipple;
void main() {
  float ripple = sin(aPosition.x * 0.72 + uTime * 0.7) * 0.55 + sin(aPosition.z * 0.58 - uTime * 0.58) * 0.3 + sin((aPosition.x + aPosition.z) * 1.1 - uTime * 0.82) * 0.15;
  vec3 world = vec3(aPosition.x, uWaterLevel + ripple * 0.026, aPosition.z);
  vWorld = world;
  vDepth = length(world - uCamPos);
  vRipple = ripple;
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform mat4 uLightViewProj;
uniform vec3 uCamPos;
uniform vec3 uLightDir;
uniform vec3 uSunColor;
uniform float uSunIntensity;
uniform vec3 uSkyColor;
uniform vec3 uDeepColor;
uniform vec3 uShallowColor;
uniform float uRoughness;
uniform float uCrestStrength;
uniform vec3 uFogColor;
uniform float uFogStart;
uniform float uFogEnd;
uniform float uFogStrength;
uniform float uTime;
uniform sampler2D uShadowMap;
uniform vec2 uShadowTexel;
uniform float uShadowBias;
uniform float uShadowStrength;
in vec3 vWorld;
in float vDepth;
in float vRipple;
out vec4 fragColor;
float specGGX(vec3 normal, vec3 lightDir, vec3 viewDir, float roughness) {
  vec3 n = normalize(normal);
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  float ndoth = max(dot(n, halfway), 0.0);
  float a = roughness * roughness;
  float a2 = a * a;
  float denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  float ndf = a2 / (3.14159265 * denom * denom);
  float ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
vec3 waterNormal(float x, float z, float time) {
  float dx = cos(x * 0.72 + time * 0.7) * 0.09 + cos((x + z) * 1.1 - time * 0.82) * 0.045;
  float dz = cos(z * 0.58 - time * 0.58) * 0.075 + cos((x + z) * 1.1 - time * 0.82) * 0.045;
  return normalize(vec3(-dx, 1.0, -dz));
}
void main() {
  vec3 normal = waterNormal(vWorld.x, vWorld.z, uTime);
  vec3 view = normalize(uCamPos - vWorld);
  vec3 light = normalize(uLightDir);
  float ndotl = max(dot(normal, light), 0.0);
  vec4 lightClip = uLightViewProj * vec4(vWorld, 1.0);
  vec2 shadowUv = ((lightClip).xy / (lightClip).w * 0.5 + 0.5);
  float receiverDepth = clamp(lightClip.z / lightClip.w * 0.5 + 0.5, 0.0, 1.0);
  float insideShadow = step(0.001, shadowUv.x) * step(shadowUv.x, 0.999) * step(0.001, shadowUv.y) * step(shadowUv.y, 0.999) * step(0.001, receiverDepth) * step(receiverDepth, 0.999) * step(0.001, lightClip.w);
  float occluded = 0.0;
  for (float i = 0.0; i < 4.0; i = i + 1.0) {
    float x = mod(i, 2.0) - 0.5;
    float y = floor(i / 2.0) - 0.5;
    vec4 stored = texture(uShadowMap, shadowUv + uShadowTexel * vec2(x, y));
    float nearestDepth = stored.x + stored.y / 255.0;
    occluded = occluded + step(nearestDepth + uShadowBias, receiverDepth);
  }
  float shadow = 1.0 - insideShadow * clamp(uShadowStrength, 0.0, 1.0) * occluded * 0.25;
  float ndotv = max(dot(normal, view), 0.0);
  float fresnel = 0.025 + 0.975 * pow(1.0 - ndotv, 5.0);
  float bodyMix = 0.18 + smoothstep(-0.72, 0.82, vRipple) * 0.18;
  vec3 body = mix(uDeepColor, uShallowColor, bodyMix);
  vec3 color = mix(body, uSkyColor, fresnel * 0.72);
  float sunSpecular = min(specGGX(normal, light, view, clamp(uRoughness, 0.08, 1.0)), 3.0) * uSunIntensity * shadow;
  float diffuseGlint = ndotl * shadow * 0.06;
  float crest = smoothstep(0.72, 0.98, vRipple) * clamp(uCrestStrength, 0.0, 1.0);
  color = color + uSunColor * (sunSpecular + diffuseGlint) + uShallowColor * (crest * 0.22);
  float fog = smoothstep(uFogStart, uFogEnd, vDepth) * clamp(uFogStrength, 0.0, 1.0);
  color = mix(color, uFogColor, fog);
  fragColor = vec4(max(color, vec3(0.0, 0.0, 0.0)), vDepth);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uLightViewProj : mat4x4f,
  uCamPos : vec3f,
  uLightDir : vec3f,
  uSunColor : vec3f,
  uSunIntensity : f32,
  uSkyColor : vec3f,
  uDeepColor : vec3f,
  uShallowColor : vec3f,
  uRoughness : f32,
  uCrestStrength : f32,
  uFogColor : vec3f,
  uFogStart : f32,
  uFogEnd : f32,
  uFogStrength : f32,
  uTime : f32,
  uWaterLevel : f32,
  uShadowTexel : vec2f,
  uShadowBias : f32,
  uShadowStrength : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uShadowMap : texture_2d<f32>;
@group(0) @binding(2) var uShadowMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vDepth : f32,
  @location(2) vRipple : f32,
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
fn waterNormal(x : f32, z : f32, time : f32) -> vec3f {
  let dx = cos(x * 0.72 + time * 0.7) * 0.09 + cos((x + z) * 1.1 - time * 0.82) * 0.045;
  let dz = cos(z * 0.58 - time * 0.58) * 0.075 + cos((x + z) * 1.1 - time * 0.82) * 0.045;
  return normalize(vec3f(-dx, 1.0, -dz));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let ripple = sin(bm_in.aPosition.x * 0.72 + bm_u.uTime * 0.7) * 0.55 + sin(bm_in.aPosition.z * 0.58 - bm_u.uTime * 0.58) * 0.3 + sin((bm_in.aPosition.x + bm_in.aPosition.z) * 1.1 - bm_u.uTime * 0.82) * 0.15;
  let world = vec3f(bm_in.aPosition.x, bm_u.uWaterLevel + ripple * 0.026, bm_in.aPosition.z);
  bm_out.vWorld = world;
  bm_out.vDepth = length(world - bm_u.uCamPos);
  bm_out.vRipple = ripple;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = waterNormal(bm_in.vWorld.x, bm_in.vWorld.z, bm_u.uTime);
  let view = normalize(bm_u.uCamPos - bm_in.vWorld);
  let light = normalize(bm_u.uLightDir);
  let ndotl = max(dot(normal, light), 0.0);
  let lightClip = bm_u.uLightViewProj * vec4f(bm_in.vWorld, 1.0);
  let shadowUv = ((lightClip).xy / (lightClip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let receiverDepth = clamp(lightClip.z / lightClip.w * 0.5 + 0.5, 0.0, 1.0);
  let insideShadow = step(0.001, shadowUv.x) * step(shadowUv.x, 0.999) * step(0.001, shadowUv.y) * step(shadowUv.y, 0.999) * step(0.001, receiverDepth) * step(receiverDepth, 0.999) * step(0.001, lightClip.w);
  var occluded = 0.0;
  for (var i = 0.0; i < 4.0; i = i + 1.0) {
    let x = ((i) - (2.0) * floor((i) / (2.0))) - 0.5;
    let y = floor(i / 2.0) - 0.5;
    let stored = textureSample(uShadowMap, uShadowMap_sampler, shadowUv + bm_u.uShadowTexel * vec2f(x, y));
    let nearestDepth = stored.x + stored.y / 255.0;
    occluded = occluded + step(nearestDepth + bm_u.uShadowBias, receiverDepth);
  }
  let shadow = 1.0 - insideShadow * clamp(bm_u.uShadowStrength, 0.0, 1.0) * occluded * 0.25;
  let ndotv = max(dot(normal, view), 0.0);
  let fresnel = 0.025 + 0.975 * pow(1.0 - ndotv, 5.0);
  let bodyMix = 0.18 + smoothstep(-0.72, 0.82, bm_in.vRipple) * 0.18;
  let body = mix(bm_u.uDeepColor, bm_u.uShallowColor, bodyMix);
  var color = mix(body, bm_u.uSkyColor, fresnel * 0.72);
  let sunSpecular = min(specGGX(normal, light, view, clamp(bm_u.uRoughness, 0.08, 1.0)), 3.0) * bm_u.uSunIntensity * shadow;
  let diffuseGlint = ndotl * shadow * 0.06;
  let crest = smoothstep(0.72, 0.98, bm_in.vRipple) * clamp(bm_u.uCrestStrength, 0.0, 1.0);
  color = color + bm_u.uSunColor * (sunSpecular + diffuseGlint) + bm_u.uShallowColor * (crest * 0.22);
  let fog = smoothstep(bm_u.uFogStart, bm_u.uFogEnd, bm_in.vDepth) * clamp(bm_u.uFogStrength, 0.0, 1.0);
  color = mix(color, bm_u.uFogColor, fog);
  return vec4f(max(color, vec3f(0.0, 0.0, 0.0)), bm_in.vDepth);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uLightViewProj: 'mat4', uCamPos: 'vec3', uLightDir: 'vec3', uSunColor: 'vec3', uSunIntensity: 'float', uSkyColor: 'vec3', uDeepColor: 'vec3', uShallowColor: 'vec3', uRoughness: 'float', uCrestStrength: 'float', uFogColor: 'vec3', uFogStart: 'float', uFogEnd: 'float', uFogStrength: 'float', uTime: 'float', uWaterLevel: 'float', uShadowMap: 'sampler2D', uShadowTexel: 'vec2', uShadowBias: 'float', uShadowStrength: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uSunColor","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uSunIntensity","type":"float","kind":"1f","size":1,"offset":172},{"name":"uSkyColor","type":"vec3","kind":"3fv","size":3,"offset":176},{"name":"uDeepColor","type":"vec3","kind":"3fv","size":3,"offset":192},{"name":"uShallowColor","type":"vec3","kind":"3fv","size":3,"offset":208},{"name":"uRoughness","type":"float","kind":"1f","size":1,"offset":220},{"name":"uCrestStrength","type":"float","kind":"1f","size":1,"offset":224},{"name":"uFogColor","type":"vec3","kind":"3fv","size":3,"offset":240},{"name":"uFogStart","type":"float","kind":"1f","size":1,"offset":252},{"name":"uFogEnd","type":"float","kind":"1f","size":1,"offset":256},{"name":"uFogStrength","type":"float","kind":"1f","size":1,"offset":260},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":264},{"name":"uWaterLevel","type":"float","kind":"1f","size":1,"offset":268},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uShadowTexel","type":"vec2","kind":"2fv","size":2,"offset":272},{"name":"uShadowBias","type":"float","kind":"1f","size":1,"offset":280},{"name":"uShadowStrength","type":"float","kind":"1f","size":1,"offset":284}],"uniformBlockSize":288},
};

export default townWaterShader;
