/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const townShadowShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uLightViewProj: 'mat4' }> = {
  vertexSrc: `#version 300 es
layout(location=0)in vec3 aPosition;uniform mat4 uLightViewProj;out vec3 vWorld;void main(){vWorld=aPosition;gl_Position=uLightViewProj*vec4(aPosition,1.0);}
`,
  fragmentSrc: `#version 300 es
precision highp float;uniform mat4 uLightViewProj;in vec3 vWorld;out vec4 fragColor;void main(){vec4 clip=uLightViewProj*vec4(vWorld,1.0);float depth=clamp(clip.z/clip.w*0.5 + 0.5,0.0,1.0);float scaled=depth*255.0;float high=floor(scaled)/255.0;float low=fract(scaled);fragColor=vec4(high,low,depth,1.0);}
`,
  wgslSrc: `struct BmUniforms {
  uLightViewProj : mat4x4f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vWorld = bm_in.aPosition;
  bm_out.bm_position = bm_u.uLightViewProj * vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let clip = bm_u.uLightViewProj * vec4f(bm_in.vWorld, 1.0);
  let depth = clamp(clip.z / clip.w * 0.5 + 0.5, 0.0, 1.0);
  let scaled = depth * 255.0;
  let high = floor(scaled) / 255.0;
  let low = fract(scaled);
  return vec4f(high, low, depth, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uLightViewProj: 'mat4' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0}],"uniformBlockSize":64},
};

export default townShadowShader;
