/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const traversalModelShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aUv: 'vec2' }, { iOffset: 'vec3'; iScale: 'vec3'; iParams: 'vec3' }, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float'; uGradeColor: 'vec3'; uGradeMix: 'float'; uWrap: 'float'; uTex: 'sampler2D'; uRamp: 'sampler3D'; uDetailNormal: 'sampler2D' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
  uGradeColor : vec3f,
  uGradeMix : f32,
  uWrap : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
@group(0) @binding(3) var uRamp : texture_3d<f32>;
@group(0) @binding(4) var uRamp_sampler : sampler;
@group(0) @binding(5) var uDetailNormal : texture_2d<f32>;
@group(0) @binding(6) var uDetailNormal_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aUv : vec2f,
  @location(3) iOffset : vec3f,
  @location(4) iScale : vec3f,
  @location(5) iParams : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vUv : vec2f,
  @location(3) vWash : f32,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn channelToLinear(channel : f32) -> f32 {
  let low = channel / 12.92;
  let high = pow((channel + 0.055) / 1.055, 2.4);
  return mix(low, high, step(0.04045, channel));
}
fn decodeSrgb(color : vec3f) -> vec3f {
  return vec3f(channelToLinear(color.x), channelToLinear(color.y), channelToLinear(color.z));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let animatedYaw = bm_in.iParams.x + sin(bm_u.uTime * 3.1 + bm_in.iParams.z) * bm_in.iParams.y;
  let rotatedPosition = rotate2(bm_in.aPosition.xz * bm_in.iScale.xz, animatedYaw);
  let rotatedNormal = rotate2(bm_in.aNormal.xz, animatedYaw);
  let world = vec3f(rotatedPosition.x + bm_in.iOffset.x, bm_in.aPosition.y * bm_in.iScale.y + bm_in.iOffset.y, rotatedPosition.y + bm_in.iOffset.z);
  bm_out.vWorld = world;
  bm_out.vNormal = normalize(vec3f(rotatedNormal.x, bm_in.aNormal.y, rotatedNormal.y));
  bm_out.vUv = bm_in.aUv;
  bm_out.vWash = 0.96 + sin(world.x * 1.7 + world.y * 2.3) * 0.04;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = decodeSrgb(textureSample(uTex, uTex_sampler, bm_in.vUv).xyz);
  let baseNormal = normalize(bm_in.vNormal);
  let detailRate = 1.1;
  let detailStrength = 0.6;
  let weightX = abs(baseNormal.x);
  let weightY = abs(baseNormal.y);
  let weightZ = abs(baseNormal.z);
  let weightSum = weightX + weightY + weightZ;
  let detailX = textureSample(uDetailNormal, uDetailNormal_sampler, vec2f(bm_in.vWorld.z, bm_in.vWorld.y) * detailRate).xyz;
  let detailY = textureSample(uDetailNormal, uDetailNormal_sampler, bm_in.vWorld.xz * detailRate).xyz;
  let detailZ = textureSample(uDetailNormal, uDetailNormal_sampler, bm_in.vWorld.xy * detailRate).xyz;
  let tiltX = detailX * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tiltY = detailY * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tiltZ = detailZ * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tilt = (vec3f(0.0, tiltX.y, tiltX.x) * weightX + vec3f(tiltY.x, 0.0, tiltY.y) * weightY + vec3f(tiltZ.x, tiltZ.y, 0.0) * weightZ) * (detailStrength / weightSum);
  let normal = normalize(baseNormal + tilt);
  let light = normalize(vec3f(-0.38, 0.84, 0.48));
  let diffuse = max((dot(normal, light) + bm_u.uWrap) / (1.0 + bm_u.uWrap), 0.0);
  let rampLight = textureSample(uRamp, uRamp_sampler, vec3f(diffuse, 0.5, 0.5)).xyz;
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let rim = pow(1.0 - max(dot(normal, view), 0.0), 2.6);
  let graded = mix(texel, bm_u.uGradeColor, bm_u.uGradeMix);
  let base = graded * rampLight * bm_in.vWash + vec3f(0.55, 0.65, 0.66) * (rim * 0.3 * bm_in.vWash);
  let distanceFog = smoothstep(22.0, 58.0, length(bm_u.uCameraPosition - bm_in.vWorld));
  return vec4f(mix(base, vec3f(0.55, 0.65, 0.66), distanceFog * 0.42), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iParams: 'vec3' },
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float', uGradeColor: 'vec3', uGradeMix: 'float', uWrap: 'float', uTex: 'sampler2D', uRamp: 'sampler3D', uDetailNormal: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0},{"name":"iOffset","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":5,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76},{"name":"uGradeColor","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uGradeMix","type":"float","kind":"1f","size":1,"offset":92},{"name":"uWrap","type":"float","kind":"1f","size":1,"offset":96},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uRamp","type":"sampler3D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uDetailNormal","type":"sampler2D","kind":"1i","size":1,"unit":2,"textureBinding":5,"samplerBinding":6}],"uniformBlockSize":112},

};

export default traversalModelShader;
