/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const traversalModelShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aUv: 'vec2' }, { iOffset: 'vec3'; iScale: 'vec3'; iParams: 'vec3' }, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float'; uTint: 'vec3'; uGradeColor: 'vec3'; uGradeMix: 'float'; uTex: 'sampler2D' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
  uTint : vec3f,
  uGradeColor : vec3f,
  uGradeMix : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aUv : vec2f,
  @location(3) iOffset : vec3f,
  @location(4) iScale : vec3f,
  @location(5) iParams : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vUv : vec2f,
  @location(3) vWash : f32,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let animatedYaw = bm_in.iParams.x + sin(bm_u.uTime * 3.1 + bm_in.iParams.z) * bm_in.iParams.y;
  let rotatedPosition = rotate2(bm_in.aPosition.xz * bm_in.iScale.xz, animatedYaw);
  let rotatedNormal = rotate2(bm_in.aNormal.xz, animatedYaw);
  let world = vec3f(rotatedPosition.x + bm_in.iOffset.x, bm_in.aPosition.y * bm_in.iScale.y + bm_in.iOffset.y, rotatedPosition.y + bm_in.iOffset.z);
  bm_out.vWorld = world;
  bm_out.vNormal = normalize(vec3f(rotatedNormal.x, bm_in.aNormal.y, rotatedNormal.y));
  bm_out.vUv = bm_in.aUv;
  bm_out.vWash = 0.96 + sin(world.x * 1.7 + world.y * 2.3) * 0.04;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uTex, uTex_sampler, bm_in.vUv).xyz;
  let normal = normalize(bm_in.vNormal);
  let light = normalize(vec3f(-0.38, 0.84, 0.48));
  let diffuse = max(dot(normal, light), 0.0);
  let band = 0.54 + smoothstep(0.18, 0.25, diffuse) * 0.2 + smoothstep(0.62, 0.7, diffuse) * 0.24;
  let graded = mix(texel, bm_u.uGradeColor, bm_u.uGradeMix);
  let base = graded * bm_u.uTint * (band * bm_in.vWash);
  let distanceFog = smoothstep(22.0, 58.0, length(bm_u.uCameraPosition - bm_in.vWorld));
  return vec4f(mix(base, vec3f(0.55, 0.65, 0.66), distanceFog * 0.42), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iParams: 'vec3' },
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float', uTint: 'vec3', uGradeColor: 'vec3', uGradeMix: 'float', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0},{"name":"iOffset","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":5,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76},{"name":"uTint","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uGradeColor","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uGradeMix","type":"float","kind":"1f","size":1,"offset":108},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":112},

};

export default traversalModelShader;
