/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const traversalHudShader: CompiledShader<{ aCorner: 'vec2' }, { iRect: 'vec4'; iColor: 'vec3'; iParams: 'vec3'; iRotation: 'float' }, Record<string, never>> = {
  wgslSrc: `struct BmVSIn {
  @location(0) aCorner : vec2f,
  @location(1) iRect : vec4f,
  @location(2) iColor : vec3f,
  @location(3) iParams : vec3f,
  @location(4) iRotation : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vLocal : vec2f,
  @location(1) vColor : vec3f,
  @location(2) vParams : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let local = bm_in.aCorner * 2.0 - vec2f(1.0, 1.0);
  bm_out.vLocal = local;
  bm_out.vColor = bm_in.iColor;
  bm_out.vParams = bm_in.iParams;
  let spin = cos(bm_in.iRotation);
  let tilt = sin(bm_in.iRotation);
  let scaledX = local.x * bm_in.iRect.z;
  let scaledY = local.y * bm_in.iRect.w;
  bm_out.bm_position = vec4f(bm_in.iRect.x + scaledX * spin - scaledY * tilt, bm_in.iRect.y + scaledX * tilt + scaledY * spin, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let fill = clamp(bm_in.vParams.x, 0.0, 1.0);
  let filled = 1.0 - clamp((bm_in.vLocal.x * 0.5 + 0.5 - fill) * 24.0, 0.0, 1.0);
  let chamfer = clamp(bm_in.vParams.z, 0.0, 0.5);
  let corner = max(bm_in.vLocal.x, 0.0 - bm_in.vLocal.x) + max(bm_in.vLocal.y, 0.0 - bm_in.vLocal.y);
  let inside = 1.0 - clamp((corner - (2.0 - chamfer)) * 12.0, 0.0, 1.0);
  let rail = 0.16;
  let brightness = rail + filled * (1.0 - rail);
  let edge = clamp((bm_in.vLocal.y - 0.62) * 6.0, 0.0, 1.0) * filled * 0.5;
  let opacity = clamp(bm_in.vParams.y, 0.0, 1.0) * inside;
  return vec4f(bm_in.vColor * brightness + bm_in.vColor * edge, min(opacity, 1.0));
}
`,
  attributes: { aCorner: 'vec2' },
  instanceAttributes: { iRect: 'vec4', iColor: 'vec3', iParams: 'vec3', iRotation: 'float' },
  uniforms: {},
  layout: {"attributes":[{"name":"aCorner","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iRect","type":"vec4","location":1,"size":4,"divisor":1},{"name":"iColor","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iRotation","type":"float","location":4,"size":1,"divisor":1}],"uniforms":[],"uniformBlockSize":0},

};

export default traversalHudShader;
