/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const arenaRippleShader: CompiledShader<{ aPosition: 'vec3' }, { iOffset: 'vec3'; iParams: 'vec3' }, { uViewProj: 'mat4'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iOffset : vec3f,
  @location(2) iParams : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vLocal : vec2f,
  @location(1) vParams : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let reach = bm_in.iParams.x + bm_in.iParams.z * 2.2;
  let world = vec4f(bm_in.aPosition.x * reach + bm_in.iOffset.x, bm_in.iOffset.y, bm_in.aPosition.y * reach + bm_in.iOffset.z, 1.0);
  bm_out.vLocal = vec2f(bm_in.aPosition.x * reach, bm_in.aPosition.y * reach);
  bm_out.vParams = bm_in.iParams;
  bm_out.bm_position = bm_u.uViewProj * world;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let distance = length(bm_in.vLocal);
  let off = distance - bm_in.vParams.x;
  let band = exp(0.0 - off * off / clamp(bm_in.vParams.z * bm_in.vParams.z, 0.0001, 100.0));
  let direction = normalize(bm_in.vLocal);
  let alive = step(0.0001, bm_in.vParams.y);
  let push = bm_in.vParams.y * band * alive;
  return vec4f(direction.x * push, direction.y * push, 0.0, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iParams: 'vec3' },
  uniforms: { uViewProj: 'mat4', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":2,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64}],"uniformBlockSize":80},

};

export default arenaRippleShader;
