/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const arenaSurfaceShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'vec3'; iColor: 'vec3'; iParams: 'vec3' }, { uSunDirection: 'vec3'; uShadowMap: 'sampler2D'; uLightViewProj: 'mat4'; uLightPosition: 'vec3'; uShadowRange: 'float'; uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uSunDirection : vec3f,
  uLightViewProj : mat4x4f,
  uLightPosition : vec3f,
  uShadowRange : f32,
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uShadowMap : texture_2d<f32>;
@group(0) @binding(2) var uShadowMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : vec3f,
  @location(4) iColor : vec3f,
  @location(5) iParams : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vColor : vec3f,
  @location(3) vParams : vec3f,
  @location(4) vPulse : f32,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn shadowDepth(worldPos : vec3f, lightPos : vec3f, range : f32) -> f32 {
  return distance(worldPos, lightPos) / range;
}
fn shadowFactor(shadowMap : texture_2d<f32>, shadowMap_sampler : sampler, lightViewProj : mat4x4f, worldPos : vec3f, normal : vec3f, lightPos : vec3f, range : f32, texel : f32, softness : f32, bias : f32) -> f32 {
  let toLight = normalize(lightPos - worldPos);
  let facing = max(dot(normalize(normal), toLight), 0.0);
  let slope = 1.0 + 2.0 * (1.0 - facing);
  let lookup = worldPos + normalize(normal) * (bias * slope);
  let clip = lightViewProj * vec4f(lookup, 1.0);
  let uv = ((clip).xy / (clip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let reference = shadowDepth(lookup, lightPos, range) - bias * slope / range;
  var visible = 0.0;
  for (var y = -1.0; y < 2.0; y = y + 1.0) {
    for (var x = -1.0; x < 2.0; x = x + 1.0) {
      let tap = uv + vec2f(x, y) * (texel * softness);
      visible = visible + step(reference, textureSampleLevel(shadowMap, shadowMap_sampler, tap, 0.0).x);
    }
  }
  return visible / 9.0;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let angle = bm_in.iParams.z;
  let rotatedPosition = rotate2(bm_in.aPosition.xz * bm_in.iScale.xz, angle);
  let rotatedNormal = rotate2(bm_in.aNormal.xz, angle);
  let bob = sin(bm_u.uTime * (2.1 + bm_in.iParams.z * 0.2) + bm_in.iOffset.x + bm_in.iOffset.z) * bm_in.iParams.x * 0.025;
  let world = vec3f(rotatedPosition.x + bm_in.iOffset.x, bm_in.aPosition.y * bm_in.iScale.y + bm_in.iOffset.y + bob, rotatedPosition.y + bm_in.iOffset.z);
  bm_out.vWorld = world;
  bm_out.vNormal = normalize(vec3f(rotatedNormal.x, bm_in.aNormal.y, rotatedNormal.y));
  bm_out.vColor = bm_in.iColor;
  bm_out.vParams = bm_in.iParams;
  bm_out.vPulse = 0.72 + sin(bm_u.uTime * 4.2 + bm_in.iOffset.x * 0.7 - bm_in.iOffset.z * 0.4) * 0.28;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = normalize(bm_in.vNormal);
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let light = normalize(vec3f(-0.52, 0.58, -0.63));
  let shadowSoftness = 2.5;
  let shadowBias = 0.03;
  let sunVisibility = shadowFactor(uShadowMap, uShadowMap_sampler, bm_u.uLightViewProj, bm_in.vWorld, normal, bm_u.uLightPosition, bm_u.uShadowRange, 0.00048828125, shadowSoftness, shadowBias);
  let diffuse = max(dot(normal, light), 0.0) * sunVisibility;
  let rim = pow(1.0 - max(dot(normal, view), 0.0), 2.1);
  let heightGlow = smoothstep(-0.45, 1.2, bm_in.vWorld.y);
  let base = bm_in.vColor * (0.16 + diffuse * 0.72) + vec3f(0.06, 0.11, 0.2) * (0.22 + normal.y * 0.18);
  let energy = bm_in.vColor * (bm_in.vParams.x * (0.35 + bm_in.vPulse * 0.65)) + vec3f(0.22, 0.6, 1.2) * (rim * (0.32 + heightGlow * 0.24));
  let hit = clamp(bm_in.vParams.y, 0.0, 1.0);
  let flashed = mix(base + energy, vec3f(2.6, 2.8, 3.2), hit * hit);
  let fog = smoothstep(17.0, 34.0, length(bm_u.uCameraPosition - bm_in.vWorld));
  return vec4f(mix(flashed, vec3f(0.001887, 0.002936, 0.004748), fog * 0.8), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iColor: 'vec3', iParams: 'vec3' },
  uniforms: { uSunDirection: 'vec3', uShadowMap: 'sampler2D', uLightViewProj: 'mat4', uLightPosition: 'vec3', uShadowRange: 'float', uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iColor","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":5,"size":3,"divisor":1}],"uniforms":[{"name":"uSunDirection","type":"vec3","kind":"3fv","size":3,"offset":0},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":16},{"name":"uLightPosition","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uShadowRange","type":"float","kind":"1f","size":1,"offset":92},{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":96},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":172}],"uniformBlockSize":176},

};

export default arenaSurfaceShader;
