/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const shipModelShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aUv: 'vec2' }, { iOffset: 'vec3'; iScale: 'vec3'; iNormalScale: 'vec3'; iTint: 'vec3'; iParams: 'vec3' }, { uSunDirection: 'vec3'; uShadowMap: 'sampler2D'; uLightViewProj: 'mat4'; uLightPosition: 'vec3'; uShadowRange: 'float'; uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTex: 'sampler2D'; uDetailNormal: 'sampler2D'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uSunDirection : vec3f,
  uLightViewProj : mat4x4f,
  uLightPosition : vec3f,
  uShadowRange : f32,
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uShadowMap : texture_2d<f32>;
@group(0) @binding(2) var uShadowMap_sampler : sampler;
@group(0) @binding(3) var uTex : texture_2d<f32>;
@group(0) @binding(4) var uTex_sampler : sampler;
@group(0) @binding(5) var uDetailNormal : texture_2d<f32>;
@group(0) @binding(6) var uDetailNormal_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aUv : vec2f,
  @location(3) iOffset : vec3f,
  @location(4) iScale : vec3f,
  @location(5) iNormalScale : vec3f,
  @location(6) iTint : vec3f,
  @location(7) iParams : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vUv : vec2f,
  @location(3) vTint : vec3f,
  @location(4) vParams : vec3f,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn shadowDepth(worldPos : vec3f, lightPos : vec3f, range : f32) -> f32 {
  return distance(worldPos, lightPos) / range;
}
fn shadowFactor(shadowMap : texture_2d<f32>, shadowMap_sampler : sampler, lightViewProj : mat4x4f, worldPos : vec3f, normal : vec3f, lightPos : vec3f, range : f32, texel : f32, softness : f32, bias : f32) -> f32 {
  let toLight = normalize(lightPos - worldPos);
  let facing = max(dot(normalize(normal), toLight), 0.0);
  let slope = 1.0 + 2.0 * (1.0 - facing);
  let lookup = worldPos + normalize(normal) * (bias * slope);
  let clip = lightViewProj * vec4f(lookup, 1.0);
  let uv = ((clip).xy / (clip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let reference = shadowDepth(lookup, lightPos, range) - bias * slope / range;
  var visible = 0.0;
  for (var y = -1.0; y < 2.0; y = y + 1.0) {
    for (var x = -1.0; x < 2.0; x = x + 1.0) {
      let tap = uv + vec2f(x, y) * (texel * softness);
      visible = visible + step(reference, textureSampleLevel(shadowMap, shadowMap_sampler, tap, 0.0).x);
    }
  }
  return visible / 9.0;
}
fn channelToLinear(channel : f32) -> f32 {
  let low = channel / 12.92;
  let high = pow((channel + 0.055) / 1.055, 2.4);
  return mix(low, high, step(0.04045, channel));
}
fn decodeSrgb(color : vec3f) -> vec3f {
  return vec3f(channelToLinear(color.x), channelToLinear(color.y), channelToLinear(color.z));
}
fn specularGGX(normal : vec3f, light : vec3f, view : vec3f, roughness : f32, f0 : vec3f) -> vec3f {
  let halfway = normalize(light + view);
  let nDotL = max(dot(normal, light), 0.0);
  let nDotV = max(dot(normal, view), 0.0001);
  let nDotH = max(dot(normal, halfway), 0.0);
  let vDotH = max(dot(view, halfway), 0.0);
  let alpha = roughness * roughness;
  let alphaSq = alpha * alpha;
  let distributionDenominator = nDotH * nDotH * (alphaSq - 1.0) + 1.0;
  let distribution = alphaSq / (3.14159265 * distributionDenominator * distributionDenominator);
  let occlusionTowardView = nDotL * sqrt(nDotV * nDotV * (1.0 - alphaSq) + alphaSq);
  let occlusionTowardLight = nDotV * sqrt(nDotL * nDotL * (1.0 - alphaSq) + alphaSq);
  let visibility = 0.5 / max(occlusionTowardView + occlusionTowardLight, 0.0001);
  let grazing = 1.0 - vDotH;
  let grazingSq = grazing * grazing;
  let fresnelWeight = grazingSq * grazingSq * grazing;
  let fresnel = f0 + (vec3f(1.0, 1.0, 1.0) - f0) * fresnelWeight;
  return fresnel * (distribution * visibility * nDotL);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let rotatedPosition = rotate2(bm_in.aPosition.xz * bm_in.iScale.xz, bm_in.iParams.z);
  let inverseScaledNormal = bm_in.aNormal * bm_in.iNormalScale;
  let rotatedNormal = rotate2(inverseScaledNormal.xz, bm_in.iParams.z);
  let world = vec3f(rotatedPosition.x + bm_in.iOffset.x, bm_in.aPosition.y * bm_in.iScale.y + bm_in.iOffset.y, rotatedPosition.y + bm_in.iOffset.z);
  bm_out.vWorld = world;
  bm_out.vNormal = normalize(vec3f(rotatedNormal.x, inverseScaledNormal.y, rotatedNormal.y));
  bm_out.vUv = bm_in.aUv;
  bm_out.vTint = bm_in.iTint;
  bm_out.vParams = bm_in.iParams;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let baseNormal = normalize(bm_in.vNormal);
  let detailRate = 0.85;
  let detailStrength = 0.35;
  let weightX = abs(baseNormal.x);
  let weightY = abs(baseNormal.y);
  let weightZ = abs(baseNormal.z);
  let weightSum = weightX + weightY + weightZ;
  let detailX = textureSample(uDetailNormal, uDetailNormal_sampler, vec2f(bm_in.vWorld.z, bm_in.vWorld.y) * detailRate).xyz;
  let detailY = textureSample(uDetailNormal, uDetailNormal_sampler, bm_in.vWorld.xz * detailRate).xyz;
  let detailZ = textureSample(uDetailNormal, uDetailNormal_sampler, bm_in.vWorld.xy * detailRate).xyz;
  let tiltX = detailX * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tiltY = detailY * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tiltZ = detailZ * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tilt = (vec3f(0.0, tiltX.y, tiltX.x) * weightX + vec3f(tiltY.x, 0.0, tiltY.y) * weightY + vec3f(tiltZ.x, tiltZ.y, 0.0) * weightZ) * (detailStrength / weightSum);
  let normal = normalize(baseNormal + tilt);
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let key = normalize(vec3f(-0.52, 0.58, -0.63));
  let shadowSoftness = 2.5;
  let shadowBias = 0.03;
  let sunVisibility = shadowFactor(uShadowMap, uShadowMap_sampler, bm_u.uLightViewProj, bm_in.vWorld, normal, bm_u.uLightPosition, bm_u.uShadowRange, 0.00048828125, shadowSoftness, shadowBias);
  let fill = normalize(vec3f(0.72, 0.3, -0.52));
  let keyLight = max(dot(normal, key), 0.0) * sunVisibility;
  let fillLight = max(dot(normal, fill), 0.0);
  let rim = pow(1.0 - max(dot(normal, view), 0.0), 2.25);
  let authored = decodeSrgb(textureSample(uTex, uTex_sampler, bm_in.vUv).xyz);
  let pulse = 0.76 + sin(bm_u.uTime * 5.4 + bm_in.vWorld.x * 0.75 - bm_in.vWorld.z * 0.52) * 0.24;
  let earthward = normalize(vec3f(-0.78, -0.42, -0.46));
  let planetFacing = dot(normal, earthward) * 0.5 + 0.5;
  let ambient = mix(vec3f(0.18, 0.18, 0.18), vec3f(1.55, 1.55, 1.55), planetFacing);
  let earthshine = vec3f(0.4, 0.5, 0.66) * ambient;
  let specular = specularGGX(normal, key, view, 0.26, vec3f(0.07, 0.07, 0.07)) * (1.9 * sunVisibility);
  let rimLight = bm_in.vTint * (rim * 0.34);
  let lit = authored * earthshine + authored * (keyLight * 1.15 + fillLight * 0.32) + specular + rimLight;
  let energy = bm_in.vTint * (clamp(bm_in.vParams.x, 0.0, 1.2) * pulse * (0.12 + rim * 0.44));
  let hit = clamp(bm_in.vParams.y, 0.0, 1.0);
  let confirmed = mix(lit + energy, vec3f(3.0, 3.15, 3.3), hit * hit);
  let fog = smoothstep(17.0, 34.0, length(bm_u.uCameraPosition - bm_in.vWorld));
  return vec4f(mix(confirmed, vec3f(0.001887, 0.002936, 0.004748), fog * 0.55), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iNormalScale: 'vec3', iTint: 'vec3', iParams: 'vec3' },
  uniforms: { uSunDirection: 'vec3', uShadowMap: 'sampler2D', uLightViewProj: 'mat4', uLightPosition: 'vec3', uShadowRange: 'float', uViewProj: 'mat4', uCameraPosition: 'vec3', uTex: 'sampler2D', uDetailNormal: 'sampler2D', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0},{"name":"iOffset","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iNormalScale","type":"vec3","location":5,"size":3,"divisor":1},{"name":"iTint","type":"vec3","location":6,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":7,"size":3,"divisor":1}],"uniforms":[{"name":"uSunDirection","type":"vec3","kind":"3fv","size":3,"offset":0},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":16},{"name":"uLightPosition","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uShadowRange","type":"float","kind":"1f","size":1,"offset":92},{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":96},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uDetailNormal","type":"sampler2D","kind":"1i","size":1,"unit":2,"textureBinding":5,"samplerBinding":6},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":172}],"uniformBlockSize":176},

};

export default shipModelShader;
