/**
 * Diffuse irradiance from `blue-photo-studio`, projected onto the first nine spherical harmonics.
 *
 * Generated by `packages/demos/scripts/bake-sh9-irradiance.mjs`. Do not hand-edit: re-run the bake.
 *
 * Blue Photo Studio — https://polyhaven.com/a/blue_photo_studio
 * CC0. Source HDRI sha256 65f086b4e9b64f4e2d01e3268a30fd98
 *
 * The convolution and basis constants are already folded in, so reconstructing irradiance for a
 * surface normal is nine multiply-adds and nothing else:
 *
 *   E(n) = c0
 *        + c1*n.y + c2*n.z + c3*n.x
 *        + c4*n.x*n.y + c5*n.y*n.z + c6*(3*n.z*n.z - 1) + c7*n.x*n.z + c8*(n.x*n.x - n.y*n.y)
 *
 * The result is reflected radiance for an albedo of 1, which is what every material shader here
 * already multiplies its albedo by — so it drops straight in where the flat ambient constant was.
 */
export const ARENA_SH9_IRRADIANCE = Object.freeze([
  [0.802638, 0.888993, 1.043646],
  [0.264819, 0.2607, 0.261858],
  [-0.457869, -0.237207, 0.035173],
  [0.644582, 0.638839, 0.645486],
  [0.133362, 0.11536, 0.093861],
  [-0.134367, -0.077254, -0.003202],
  [0.126323, 0.115655, 0.114423],
  [-0.692762, -0.71153, -0.790787],
  [0.192922, 0.24485, 0.327036],
] as const);
