/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const arenaModelShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aUv: 'vec2' }, { iOffset: 'vec3'; iScale: 'vec3'; iTint: 'vec3'; iParams: 'vec3' }, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTex: 'sampler2D'; uDetailNormal: 'sampler2D'; uKitMaterials: 'sampler3D'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
@group(0) @binding(3) var uDetailNormal : texture_2d<f32>;
@group(0) @binding(4) var uDetailNormal_sampler : sampler;
@group(0) @binding(5) var uKitMaterials : texture_3d<f32>;
@group(0) @binding(6) var uKitMaterials_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aUv : vec2f,
  @location(3) iOffset : vec3f,
  @location(4) iScale : vec3f,
  @location(5) iTint : vec3f,
  @location(6) iParams : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vUv : vec2f,
  @location(3) vTint : vec3f,
  @location(4) vParams : vec3f,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn channelToLinear(channel : f32) -> f32 {
  let low = channel / 12.92;
  let high = pow((channel + 0.055) / 1.055, 2.4);
  return mix(low, high, step(0.04045, channel));
}
fn decodeSrgb(color : vec3f) -> vec3f {
  return vec3f(channelToLinear(color.x), channelToLinear(color.y), channelToLinear(color.z));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let rotatedPosition = rotate2(bm_in.aPosition.xz * bm_in.iScale.xz, bm_in.iParams.z);
  let rotatedNormal = rotate2(bm_in.aNormal.xz, bm_in.iParams.z);
  let world = vec3f(rotatedPosition.x + bm_in.iOffset.x, bm_in.aPosition.y * bm_in.iScale.y + bm_in.iOffset.y, rotatedPosition.y + bm_in.iOffset.z);
  bm_out.vWorld = world;
  bm_out.vNormal = normalize(vec3f(rotatedNormal.x, bm_in.aNormal.y, rotatedNormal.y));
  bm_out.vUv = bm_in.aUv;
  bm_out.vTint = bm_in.iTint;
  bm_out.vParams = bm_in.iParams;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let baseNormal = normalize(bm_in.vNormal);
  let detailRate = 0.25;
  let detailStrength = 0.55;
  let weightX = abs(baseNormal.x);
  let weightY = abs(baseNormal.y);
  let weightZ = abs(baseNormal.z);
  let weightSum = weightX + weightY + weightZ;
  let detailX = textureSample(uDetailNormal, uDetailNormal_sampler, vec2f(bm_in.vWorld.z, bm_in.vWorld.y) * detailRate).xyz;
  let detailY = textureSample(uDetailNormal, uDetailNormal_sampler, bm_in.vWorld.xz * detailRate).xyz;
  let detailZ = textureSample(uDetailNormal, uDetailNormal_sampler, bm_in.vWorld.xy * detailRate).xyz;
  let tiltX = detailX * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tiltY = detailY * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tiltZ = detailZ * 2.0 - vec3f(1.0, 1.0, 1.0);
  let tilt = (vec3f(0.0, tiltX.y, tiltX.x) * weightX + vec3f(tiltY.x, 0.0, tiltY.y) * weightY + vec3f(tiltZ.x, tiltZ.y, 0.0) * weightZ) * (detailStrength / weightSum);
  let normal = normalize(baseNormal + tilt);
  let light = normalize(vec3f(-0.44, 0.86, 0.42));
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let diffuse = max(dot(normal, light), 0.0);
  let kitRoughness = textureSample(uKitMaterials, uKitMaterials_sampler, vec3f(bm_in.vUv.x, bm_in.vUv.y, 0.5)).x;
  let rim = pow(1.0 - max(dot(normal, view), 0.0), 2.2) * (1.25 - kitRoughness);
  let sampled = decodeSrgb(textureSample(uTex, uTex_sampler, bm_in.vUv).xyz) * bm_in.vTint;
  let fill = max(normal.y, 0.0) * 0.1;
  let pulse = 0.72 + sin(bm_u.uTime * 5.2 + bm_in.vWorld.x * 0.8 - bm_in.vWorld.z * 0.55) * 0.28;
  let lit = sampled * (0.16 + diffuse * 0.74 + fill) + bm_in.vTint * (clamp(bm_in.vParams.x, 0.0, 1.0) * pulse * (0.12 + rim * 0.34));
  let confirmed = mix(lit, vec3f(1.7, 1.8, 1.9), clamp(bm_in.vParams.y, 0.0, 1.0));
  let fog = smoothstep(17.0, 34.0, length(bm_u.uCameraPosition - bm_in.vWorld));
  return vec4f(tonemapACES(mix(confirmed, vec3f(0.006, 0.01, 0.018), fog * 0.72)), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iTint: 'vec3', iParams: 'vec3' },
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uTex: 'sampler2D', uDetailNormal: 'sampler2D', uKitMaterials: 'sampler3D', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0},{"name":"iOffset","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iTint","type":"vec3","location":5,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":6,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uDetailNormal","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uKitMaterials","type":"sampler3D","kind":"1i","size":1,"unit":2,"textureBinding":5,"samplerBinding":6},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76}],"uniformBlockSize":80},

};

export default arenaModelShader;
