/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const arenaRibbonShader: CompiledShader<{ aPosition: 'vec3' }, { iStart: 'vec3'; iEnd: 'vec3'; iColor: 'vec3'; iParams: 'vec3' }, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float'; uBillboard: 'sampler2D' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uBillboard : texture_2d<f32>;
@group(0) @binding(2) var uBillboard_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iStart : vec3f,
  @location(2) iEnd : vec3f,
  @location(3) iColor : vec3f,
  @location(4) iParams : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vColor : vec3f,
  @location(2) vStrength : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let along = bm_in.iStart + (bm_in.iEnd - bm_in.iStart) * bm_in.aPosition.x;
  let side = normalize(cross(bm_in.iEnd - bm_in.iStart, bm_u.uCameraPosition - along));
  let width = bm_in.iParams.x * (0.55 + bm_in.aPosition.x * 0.45);
  let world = along + side * (width * bm_in.aPosition.y);
  bm_out.vUv = vec2f(bm_in.aPosition.x, bm_in.aPosition.y * 0.5 + 0.5);
  bm_out.vColor = bm_in.iColor;
  bm_out.vStrength = bm_in.iParams.y * bm_in.iParams.z;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let profile = textureSample(uBillboard, uBillboard_sampler, vec2f(0.5, bm_in.vUv.y)).x;
  let alive = step(0.0001, bm_in.vStrength);
  return vec4f(bm_in.vColor * (profile * bm_in.vStrength * alive), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iStart: 'vec3', iEnd: 'vec3', iColor: 'vec3', iParams: 'vec3' },
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float', uBillboard: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iStart","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iEnd","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iColor","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":4,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76},{"name":"uBillboard","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":80},

};

export default arenaRibbonShader;
