/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const bloomExtractShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uScene: 'sampler2D'; uThreshold: 'float'; uTexel: 'vec2' }> = {
  wgslSrc: `struct BmUniforms {
  uThreshold : f32,
  uTexel : vec2f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uScene : texture_2d<f32>;
@group(0) @binding(2) var uScene_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = ((vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).xy / (vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).w * vec2f(0.5, -0.5) + vec2f(0.5));
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let offset = vec2f(bm_u.uTexel.x * 0.25, bm_u.uTexel.y * 0.25);
  let scene = (textureSample(uScene, uScene_sampler, vec2f(bm_in.vUv.x - offset.x, bm_in.vUv.y - offset.y)).xyz + textureSample(uScene, uScene_sampler, vec2f(bm_in.vUv.x + offset.x, bm_in.vUv.y - offset.y)).xyz + textureSample(uScene, uScene_sampler, vec2f(bm_in.vUv.x - offset.x, bm_in.vUv.y + offset.y)).xyz + textureSample(uScene, uScene_sampler, vec2f(bm_in.vUv.x + offset.x, bm_in.vUv.y + offset.y)).xyz) * 0.25;
  let brightest = max(max(scene.x, scene.y), scene.z);
  let overflow = max(brightest - bm_u.uThreshold, 0.0) / max(brightest, 0.0001);
  return vec4f(scene * overflow, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uScene: 'sampler2D', uThreshold: 'float', uTexel: 'vec2' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uScene","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uThreshold","type":"float","kind":"1f","size":1,"offset":0},{"name":"uTexel","type":"vec2","kind":"2fv","size":2,"offset":8}],"uniformBlockSize":16},

};

export default bloomExtractShader;
