/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const earthGlobeShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float'; uCenter: 'vec3'; uRadius: 'float'; uAlbedo: 'sampler2D'; uClouds: 'sampler2D' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
  uCenter : vec3f,
  uRadius : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAlbedo : texture_2d<f32>;
@group(0) @binding(2) var uAlbedo_sampler : sampler;
@group(0) @binding(3) var uClouds : texture_2d<f32>;
@group(0) @binding(4) var uClouds_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vWorld : vec3f,
}
fn channelToLinear(channel : f32) -> f32 {
  let low = channel / 12.92;
  let high = pow((channel + 0.055) / 1.055, 2.4);
  return mix(low, high, step(0.04045, channel));
}
fn decodeSrgb(color : vec3f) -> vec3f {
  return vec3f(channelToLinear(color.x), channelToLinear(color.y), channelToLinear(color.z));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = bm_in.aPosition * bm_u.uRadius + bm_u.uCenter;
  bm_out.vNormal = normalize(bm_in.aNormal);
  bm_out.vWorld = world;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = normalize(bm_in.vNormal);
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let latitude = asin(clamp(normal.y, -1.0, 1.0));
  let surfaceSpin = bm_u.uTime * 0.018;
  let surfaceLongitude = atan2(normal.z, normal.x) + surfaceSpin;
  let surfaceUv = vec2f(surfaceLongitude * 0.159155 + 0.5, 0.5 - latitude * 0.31831);
  let surface = decodeSrgb(textureSample(uAlbedo, uAlbedo_sampler, surfaceUv).xyz);
  let cloudLongitude = atan2(normal.z, normal.x) + bm_u.uTime * 0.031;
  let cloudUv = vec2f(cloudLongitude * 0.159155 + 0.5, 0.5 - latitude * 0.31831);
  let cloudDensity = clamp(textureSample(uClouds, uClouds_sampler, cloudUv).x * 1.25, 0.0, 1.0);
  let sun = normalize(vec3f(-0.44, 0.86, 0.42));
  let lambert = max(dot(normal, sun), 0.0);
  let dayNight = clamp(lambert * 1.35 + 0.06, 0.0, 1.25);
  let night = vec3f(0.012, 0.018, 0.035);
  let oceanMask = clamp((surface.z - surface.x) * 3.4, 0.0, 1.0);
  let glint = pow(max(dot(normalize(sun + view), normal), 0.0), 90.0) * oceanMask * lambert;
  let litSurface = surface * dayNight + vec3f(0.28, 0.44, 0.75) * (glint * 0.5);
  let litClouds = vec3f(0.95, 0.96, 0.99) * (dayNight * 0.92);
  let daySide = mix(litSurface, litClouds, cloudDensity * 0.82);
  let withNight = mix(night, daySide, clamp(lambert * 2.4 + 0.08, 0.0, 1.0));
  let rim = pow(1.0 - max(dot(normal, view), 0.0), 2.6);
  let haze = vec3f(0.24, 0.52, 0.95) * (rim * (0.35 + max(dot(normal, sun), 0.0) * 1.5));
  return vec4f(withNight + haze, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float', uCenter: 'vec3', uRadius: 'float', uAlbedo: 'sampler2D', uClouds: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76},{"name":"uCenter","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uRadius","type":"float","kind":"1f","size":1,"offset":92},{"name":"uAlbedo","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uClouds","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4}],"uniformBlockSize":96},

};

export default earthGlobeShader;
