/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const postShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uScene: 'sampler2D'; uBloom: 'sampler2D'; uBloomStrength: 'float'; uExposure: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uBloomStrength : f32,
  uExposure : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uScene : texture_2d<f32>;
@group(0) @binding(2) var uScene_sampler : sampler;
@group(0) @binding(3) var uBloom : texture_2d<f32>;
@group(0) @binding(4) var uBloom_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn channelToDisplay(channel : f32) -> f32 {
  let safe = max(channel, 0.0);
  let low = safe * 12.92;
  let high = pow(safe, 0.4166666666666667) * 1.055 - 0.055;
  return mix(low, high, step(0.0031308, safe));
}
fn shapeContrast(channel : f32) -> f32 {
  return 0.18 * pow(max(channel, 0.0) / 0.18, 1.16);
}
fn encodeSrgb(color : vec3f) -> vec3f {
  return vec3f(channelToDisplay(color.x), channelToDisplay(color.y), channelToDisplay(color.z));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = ((vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).xy / (vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).w * vec2f(0.5, -0.5) + vec2f(0.5));
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let scene = textureSample(uScene, uScene_sampler, bm_in.vUv).xyz;
  let withBloom = scene + textureSample(uBloom, uBloom_sampler, bm_in.vUv).xyz * bm_u.uBloomStrength;
  let exposed = withBloom * bm_u.uExposure;
  let grey = exposed.x * 0.2126 + exposed.y * 0.7152 + exposed.z * 0.0722;
  let saturated = mix(vec3f(grey, grey, grey), exposed, 1.1);
  let graded = vec3f(shapeContrast(saturated.x), shapeContrast(saturated.y), shapeContrast(saturated.z));
  let centred = bm_in.vUv - vec2f(0.5, 0.5);
  let vignette = 1.0 - smoothstep(0.28, 0.78, length(centred)) * 0.2;
  return vec4f(encodeSrgb(tonemapACES(graded * vignette)), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uScene: 'sampler2D', uBloom: 'sampler2D', uBloomStrength: 'float', uExposure: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uScene","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uBloom","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uBloomStrength","type":"float","kind":"1f","size":1,"offset":0},{"name":"uExposure","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},

};

export default postShader;
