/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const shipModelShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aUv: 'vec2' }, { iOffset: 'vec3'; iScale: 'vec3'; iNormalScale: 'vec3'; iTint: 'vec3'; iParams: 'vec3' }, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTex: 'sampler2D'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aUv : vec2f,
  @location(3) iOffset : vec3f,
  @location(4) iScale : vec3f,
  @location(5) iNormalScale : vec3f,
  @location(6) iTint : vec3f,
  @location(7) iParams : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vUv : vec2f,
  @location(3) vTint : vec3f,
  @location(4) vParams : vec3f,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let rotatedPosition = rotate2(bm_in.aPosition.xz * bm_in.iScale.xz, bm_in.iParams.z);
  let inverseScaledNormal = bm_in.aNormal * bm_in.iNormalScale;
  let rotatedNormal = rotate2(inverseScaledNormal.xz, bm_in.iParams.z);
  let world = vec3f(rotatedPosition.x + bm_in.iOffset.x, bm_in.aPosition.y * bm_in.iScale.y + bm_in.iOffset.y, rotatedPosition.y + bm_in.iOffset.z);
  bm_out.vWorld = world;
  bm_out.vNormal = normalize(vec3f(rotatedNormal.x, inverseScaledNormal.y, rotatedNormal.y));
  bm_out.vUv = bm_in.aUv;
  bm_out.vTint = bm_in.iTint;
  bm_out.vParams = bm_in.iParams;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = normalize(bm_in.vNormal);
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let key = normalize(vec3f(-0.44, 0.86, 0.42));
  let fill = normalize(vec3f(0.72, 0.3, -0.52));
  let keyLight = max(dot(normal, key), 0.0);
  let fillLight = max(dot(normal, fill), 0.0);
  let rim = pow(1.0 - max(dot(normal, view), 0.0), 2.25);
  let authored = textureSample(uTex, uTex_sampler, bm_in.vUv).xyz;
  let pulse = 0.76 + sin(bm_u.uTime * 5.4 + bm_in.vWorld.x * 0.75 - bm_in.vWorld.z * 0.52) * 0.24;
  let lit = authored * (0.25 + keyLight * 1.02 + fillLight * 0.28) + vec3f(0.025, 0.045, 0.075) * (0.4 + max(normal.y, 0.0) * 0.34);
  let energy = bm_in.vTint * (clamp(bm_in.vParams.x, 0.0, 1.2) * pulse * (0.12 + rim * 0.44));
  let hit = clamp(bm_in.vParams.y, 0.0, 1.0);
  let confirmed = mix(lit + energy, vec3f(3.0, 3.15, 3.3), hit * hit);
  let fog = smoothstep(17.0, 34.0, length(bm_u.uCameraPosition - bm_in.vWorld));
  return vec4f(tonemapACES(mix(confirmed, vec3f(0.004, 0.009, 0.02), fog * 0.55)), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iNormalScale: 'vec3', iTint: 'vec3', iParams: 'vec3' },
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uTex: 'sampler2D', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0},{"name":"iOffset","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iNormalScale","type":"vec3","location":5,"size":3,"divisor":1},{"name":"iTint","type":"vec3","location":6,"size":3,"divisor":1},{"name":"iParams","type":"vec3","location":7,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76}],"uniformBlockSize":80},

};

export default shipModelShader;
