/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const spaceBackdropShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = vec3f(bm_in.aPosition.x, -1.45, bm_in.aPosition.z);
  bm_out.vWorld = world;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let coordinates = bm_in.vWorld.xz;
  let starSeed = fract(sin(dot(coordinates, vec2f(12.9898, 78.233))) * 43758.5453);
  let sparseStars = pow(max(starSeed, 0.0), 72.0) * (0.66 + sin(bm_u.uTime * 0.45 + starSeed * 16.0) * 0.12);
  let nebula = clamp(sin(coordinates.x * 0.105 + coordinates.y * 0.062) * sin(coordinates.y * 0.086 - coordinates.x * 0.034) * 0.5 + 0.5, 0.0, 1.0);
  let planetVector = coordinates - vec2f(-16.5, -12.5);
  let planetDistance = length(planetVector);
  let planetDisc = 1.0 - smoothstep(7.35, 7.85, planetDistance);
  let atmosphere = clamp(1.0 - smoothstep(7.8, 10.25, planetDistance) - planetDisc, 0.0, 1.0);
  let limb = pow(clamp(1.0 - planetDistance / 7.85, 0.0, 1.0), 0.34);
  let cloudBands = 0.5 + sin(planetVector.y * 1.28 + sin(planetVector.x * 0.42) * 1.6) * 0.5;
  let planet = mix(vec3f(0.018, 0.045, 0.09), vec3f(0.075, 0.18, 0.27), limb) + vec3f(0.08, 0.12, 0.14) * (cloudBands * 0.18);
  let space = vec3f(0.0015, 0.004, 0.012) + vec3f(0.008, 0.016, 0.032) * (nebula * 0.7) + vec3f(0.68, 0.78, 0.94) * (sparseStars * (1.0 - planetDisc));
  let withPlanet = mix(space, planet, planetDisc);
  let withAtmosphere = withPlanet + vec3f(0.04, 0.22, 0.34) * (atmosphere * atmosphere * 1.25);
  return vec4f(tonemapACES(withAtmosphere), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64}],"uniformBlockSize":80},

};

export default spaceBackdropShader;
