/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const spaceBackdropShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = vec3f(bm_in.aPosition.x, -1.45, bm_in.aPosition.z);
  bm_out.vWorld = world;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let coordinates = bm_in.vWorld.xz;
  let starSeed = fract(sin(dot(coordinates, vec2f(12.9898, 78.233))) * 43758.5453);
  let sparseStars = pow(max(starSeed, 0.0), 72.0) * (0.66 + sin(bm_u.uTime * 0.45 + starSeed * 16.0) * 0.12);
  let nebula = clamp(sin(coordinates.x * 0.105 + coordinates.y * 0.062) * sin(coordinates.y * 0.086 - coordinates.x * 0.034) * 0.5 + 0.5, 0.0, 1.0);
  let planetVector = coordinates - vec2f(-14.0, -14.0);
  let planetDistance = length(planetVector);
  let planetRadius = 12.0;
  let planetDisc = 1.0 - smoothstep(planetRadius - 0.5, planetRadius, planetDistance);
  let atmosphere = clamp(1.0 - smoothstep(planetRadius - 0.1, planetRadius + 4.6, planetDistance) - planetDisc, 0.0, 1.0);
  let limb = pow(clamp(1.0 - planetDistance / planetRadius, 0.0, 1.0), 0.34);
  let cloudBands = clamp(0.5 + sin(planetVector.y * 0.42 + sin(planetVector.x * 0.23) * 2.1) * 0.5 + sin(planetVector.x * 0.31 - planetVector.y * 0.17) * 0.22 + sin(planetVector.y * 0.83 + planetVector.x * 0.29) * 0.16, 0.0, 1.0);
  let landField = 0.5 + sin(planetVector.x * 0.19 + 1.7) * sin(planetVector.y * 0.24 - 0.6) * 0.36 + sin(planetVector.x * 0.47 - 0.9) * sin(planetVector.y * 0.39 + 2.2) * 0.2;
  let land = smoothstep(0.62, 0.78, landField) * planetDisc;
  let dayside = clamp(0.46 + (0.0 - planetVector.x) * 0.038 + planetVector.y * 0.022, 0.0, 1.2);
  let ocean = mix(vec3f(0.035, 0.16, 0.42), vec3f(0.12, 0.36, 0.72), limb);
  let continents = mix(vec3f(0.16, 0.26, 0.13), vec3f(0.42, 0.36, 0.22), landField);
  let planet = (mix(ocean, continents, land * 0.85) + vec3f(0.86, 0.9, 0.95) * (cloudBands * 0.34)) * dayside;
  let space = vec3f(0.0015, 0.004, 0.012) + vec3f(0.008, 0.016, 0.032) * (nebula * 0.7) + vec3f(0.68, 0.78, 0.94) * (sparseStars * (1.0 - planetDisc));
  let withPlanet = mix(space, planet, planetDisc);
  let withAtmosphere = withPlanet + vec3f(0.16, 0.44, 0.86) * (atmosphere * atmosphere * 1.9 * dayside);
  return vec4f(tonemapACES(withAtmosphere), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64}],"uniformBlockSize":80},

};

export default spaceBackdropShader;
