/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const spaceBackdropShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uStarMap: 'sampler2D'; uCameraPosition: 'vec3'; uTime: 'float'; uViewProj: 'mat4' }> = {
  wgslSrc: `struct BmUniforms {
  uCameraPosition : vec3f,
  uTime : f32,
  uViewProj : mat4x4f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uStarMap : texture_2d<f32>;
@group(0) @binding(2) var uStarMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
}
fn channelToScene(channel : f32) -> f32 {
  let safe = clamp(channel, 0.0, 0.9999);
  let a = 2.43 * safe - 2.51;
  let b = 0.59 * safe - 0.03;
  let c = 0.14 * safe;
  return (0.0 - b - sqrt(max(b * b - 4.0 * a * c, 0.0))) / (2.0 * a);
}
fn inverseTonemapACES(color : vec3f) -> vec3f {
  return vec3f(channelToScene(color.x), channelToScene(color.y), channelToScene(color.z));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vWorld = bm_in.aPosition;
  bm_out.bm_position = bm_u.uViewProj * vec4f(bm_in.aPosition + bm_u.uCameraPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let direction = normalize(bm_in.vWorld);
  let longitude = atan2(direction.z, direction.x);
  let latitude = asin(clamp(direction.y, -1.0, 1.0));
  let skyUv = vec2f(longitude * 0.159155 + 0.5, 0.5 - latitude * 0.31831);
  let band = textureSample(uStarMap, uStarMap_sampler, skyUv).xyz;
  let gridAX = skyUv.x * 900.0;
  let gridAY = skyUv.y * 450.0;
  let cellA = fract(sin(dot(vec2f(floor(gridAX), floor(gridAY)), vec2f(12.9898, 78.233))) * 43758.5453);
  let offsetA = vec2f(fract(gridAX) - (0.25 + fract(cellA * 31.7) * 0.5), fract(gridAY) - (0.25 + fract(cellA * 17.3) * 0.5));
  let gridBX = skyUv.x * 420.0;
  let gridBY = skyUv.y * 210.0;
  let cellB = fract(sin(dot(vec2f(floor(gridBX), floor(gridBY)), vec2f(39.3468, 11.135))) * 24634.6345);
  let offsetB = vec2f(fract(gridBX) - (0.25 + fract(cellB * 27.1) * 0.5), fract(gridBY) - (0.25 + fract(cellB * 13.9) * 0.5));
  let gridCX = skyUv.x * 170.0;
  let gridCY = skyUv.y * 85.0;
  let cellC = fract(sin(dot(vec2f(floor(gridCX), floor(gridCY)), vec2f(63.7264, 10.873))) * 31879.1234);
  let offsetC = vec2f(fract(gridCX) - (0.25 + fract(cellC * 23.3) * 0.5), fract(gridCY) - (0.25 + fract(cellC * 41.1) * 0.5));
  let twinkleA = 0.72 + sin(bm_u.uTime * (1.4 + cellA * 2.6) + cellA * 63.0) * 0.28;
  let twinkleB = 0.78 + sin(bm_u.uTime * (0.9 + cellB * 1.8) + cellB * 47.0) * 0.22;
  let twinkleC = 0.84 + sin(bm_u.uTime * (0.6 + cellC * 1.2) + cellC * 29.0) * 0.16;
  let faint = step(0.986, cellA) * (1.0 - smoothstep(0.0, 0.055, length(offsetA))) * twinkleA;
  let middling = step(0.976, cellB) * (1.0 - smoothstep(0.0, 0.05, length(offsetB))) * twinkleB;
  let bright = step(0.972, cellC) * (1.0 - smoothstep(0.0, 0.045, length(offsetC))) * twinkleC;
  let starLight = vec3f(0.78, 0.84, 1.0) * (bright * 1.15) + vec3f(0.86, 0.86, 0.84) * (middling * 0.8) + vec3f(0.84, 0.76, 0.66) * (faint * 0.5);
  return vec4f(inverseTonemapACES(band * 1.15 + starLight + vec3f(0.004, 0.005, 0.011)), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uStarMap: 'sampler2D', uCameraPosition: 'vec3', uTime: 'float', uViewProj: 'mat4' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uStarMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":12},{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":16}],"uniformBlockSize":80},

};

export default spaceBackdropShader;
