/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const courseSkyShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vWorld = bm_in.aPosition;
  bm_out.bm_position = bm_u.uViewProj * vec4f(bm_in.aPosition + bm_u.uCameraPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let direction = normalize(bm_in.vWorld);
  let height = clamp(direction.y, -0.35, 1.0);
  let above = clamp(height, 0.0, 1.0);
  let horizonBand = pow(1.0 - above, 9.0) * smoothstep(-0.1, 0.005, height);
  let zenith = vec3f(0.075, 0.19, 0.4);
  let mid = vec3f(0.19, 0.35, 0.53);
  let horizon = vec3f(0.66, 0.52, 0.34);
  let base = zenith + (mid - zenith) * clamp(1.0 - above * 3.2, 0.0, 1.0);
  let below = clamp(0.0 - height, 0.0, 1.0);
  let sea = vec3f(0.085, 0.14, 0.19);
  let skyAbove = base + (horizon - base) * horizonBand;
  let sky = skyAbove * (1.0 - smoothstep(0.0, 0.18, below)) + sea * smoothstep(0.0, 0.18, below);
  let toSun = normalize(vec3f(0.55, 0.16, -0.8));
  let sunness = max(direction.x * toSun.x + direction.y * toSun.y + direction.z * toSun.z, 0.0);
  let glow = vec3f(0.9, 0.62, 0.34) * (exp((sunness - 1.0) * 11.0) * 0.6);
  return vec4f(sky + glow, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76}],"uniformBlockSize":80},

};

export default courseSkyShader;
