/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const traversalSurfaceShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'vec3'; iColor: 'vec3'; iMaterial: 'vec3' }, { uSunDirection: 'vec3'; uShadowMap: 'sampler2D'; uLightViewProj: 'mat4'; uLightPosition: 'vec3'; uShadowRange: 'float'; uBillboard: 'sampler2D'; uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uSunDirection : vec3f,
  uLightViewProj : mat4x4f,
  uLightPosition : vec3f,
  uShadowRange : f32,
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uShadowMap : texture_2d<f32>;
@group(0) @binding(2) var uShadowMap_sampler : sampler;
@group(0) @binding(3) var uBillboard : texture_2d<f32>;
@group(0) @binding(4) var uBillboard_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : vec3f,
  @location(4) iColor : vec3f,
  @location(5) iMaterial : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vColor : vec3f,
  @location(3) vMaterial : vec3f,
  @location(4) vPulse : f32,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn shadowDepth(worldPos : vec3f, lightPos : vec3f, range : f32) -> f32 {
  return distance(worldPos, lightPos) / range;
}
fn shadowFactor(shadowMap : texture_2d<f32>, shadowMap_sampler : sampler, lightViewProj : mat4x4f, worldPos : vec3f, normal : vec3f, lightPos : vec3f, range : f32, texel : f32, softness : f32, bias : f32) -> f32 {
  let toLight = normalize(lightPos - worldPos);
  let facing = max(dot(normalize(normal), toLight), 0.0);
  let slope = 1.0 + 2.0 * (1.0 - facing);
  let lookup = worldPos + normalize(normal) * (bias * slope);
  let clip = lightViewProj * vec4f(lookup, 1.0);
  let uv = ((clip).xy / (clip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let reference = shadowDepth(lookup, lightPos, range) - bias * slope / range;
  var visible = 0.0;
  for (var y = -1.0; y < 2.0; y = y + 1.0) {
    for (var x = -1.0; x < 2.0; x = x + 1.0) {
      let tap = uv + vec2f(x, y) * (texel * softness);
      visible = visible + step(reference, textureSampleLevel(shadowMap, shadowMap_sampler, tap, 0.0).x);
    }
  }
  return visible / 9.0;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let rotatedPosition = rotate2(bm_in.aPosition.xy * bm_in.iScale.xy, bm_in.iMaterial.z);
  let rotatedNormal = rotate2(bm_in.aNormal.xy, bm_in.iMaterial.z);
  let world = vec3f(rotatedPosition.x + bm_in.iOffset.x, rotatedPosition.y + bm_in.iOffset.y, bm_in.aPosition.z * bm_in.iScale.z + bm_in.iOffset.z);
  bm_out.vWorld = world;
  bm_out.vNormal = normalize(vec3f(rotatedNormal.x, rotatedNormal.y, bm_in.aNormal.z));
  bm_out.vColor = bm_in.iColor;
  bm_out.vMaterial = bm_in.iMaterial;
  bm_out.vPulse = 0.74 + sin(bm_u.uTime * 3.6 + bm_in.iOffset.x * 0.28 + bm_in.iOffset.y) * 0.26;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = normalize(bm_in.vNormal);
  let light = normalize(vec3f(-0.38, 0.84, 0.48));
  let shadowSoftness = 2.5;
  let shadowBias = 0.05;
  let sunVisibility = shadowFactor(uShadowMap, uShadowMap_sampler, bm_u.uLightViewProj, bm_in.vWorld, normal, bm_u.uLightPosition, bm_u.uShadowRange, 0.00048828125, shadowSoftness, shadowBias);
  let view = normalize(bm_u.uCameraPosition - bm_in.vWorld);
  let rawLight = max(dot(normal, light), 0.0) * sunVisibility;
  let litBand = smoothstep(0.18, 0.24, rawLight) * 0.28 + smoothstep(0.58, 0.64, rawLight) * 0.48;
  let rim = pow(1.0 - max(dot(normal, view), 0.0), 2.2);
  let base = bm_in.vColor * (0.48 + litBand) + vec3f(0.16, 0.2, 0.18) * (0.12 + normal.y * 0.08);
  let emissive = bm_in.vColor * (bm_in.vMaterial.x * (0.16 + bm_in.vPulse * 0.24));
  let highlight = vec3f(1.05, 0.83, 0.48) * (clamp(bm_in.vMaterial.y, 0.0, 1.0) * (0.16 + rim * 0.3));
  let depth = smoothstep(22.0, 58.0, length(bm_u.uCameraPosition - bm_in.vWorld));
  let surfaceNormal = normalize(bm_in.vNormal);
  let structure = textureSample(uBillboard, uBillboard_sampler, vec2f(surfaceNormal.x * 0.5 + 0.5, surfaceNormal.z * 0.5 + 0.5)).w;
  let textured = 0.6 + structure * 0.4;
  let composed = (base + emissive + highlight) * textured;
  return vec4f(mix(composed, vec3f(0.096296, 0.190755, 0.284863), depth * 0.5), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iColor: 'vec3', iMaterial: 'vec3' },
  uniforms: { uSunDirection: 'vec3', uShadowMap: 'sampler2D', uLightViewProj: 'mat4', uLightPosition: 'vec3', uShadowRange: 'float', uBillboard: 'sampler2D', uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iColor","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iMaterial","type":"vec3","location":5,"size":3,"divisor":1}],"uniforms":[{"name":"uSunDirection","type":"vec3","kind":"3fv","size":3,"offset":0},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":16},{"name":"uLightPosition","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uShadowRange","type":"float","kind":"1f","size":1,"offset":92},{"name":"uBillboard","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":96},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":172}],"uniformBlockSize":176},

};

export default traversalSurfaceShader;
