/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const traversalGlowShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'vec3'; iColor: 'vec3'; iAlpha: 'float'; iRotation: 'float'; iPhase: 'float' }, { uBillboard: 'sampler2D'; uViewProj: 'mat4'; uCameraPosition: 'vec3'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCameraPosition : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uBillboard : texture_2d<f32>;
@group(0) @binding(2) var uBillboard_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : vec3f,
  @location(4) iColor : vec3f,
  @location(5) iAlpha : f32,
  @location(6) iRotation : f32,
  @location(7) iPhase : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vColor : vec3f,
  @location(3) vAlpha : f32,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let rotatedPosition = rotate2(bm_in.aPosition.xy * bm_in.iScale.xy, bm_in.iRotation);
  let rotatedNormal = rotate2(bm_in.aNormal.xy, bm_in.iRotation);
  let world = vec3f(rotatedPosition.x + bm_in.iOffset.x, rotatedPosition.y + bm_in.iOffset.y, bm_in.aPosition.z * bm_in.iScale.z + bm_in.iOffset.z);
  bm_out.vWorld = world;
  bm_out.vNormal = normalize(vec3f(rotatedNormal.x, rotatedNormal.y, bm_in.aNormal.z));
  bm_out.vColor = bm_in.iColor;
  bm_out.vAlpha = bm_in.iAlpha * (0.8 + sin(bm_u.uTime * (3.9 + bm_in.iPhase * 1.8) + bm_in.iPhase) * 0.2);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let facing = max(dot(normalize(bm_in.vNormal), normalize(bm_u.uCameraPosition - bm_in.vWorld)), 0.0);
  let core = pow(facing, 2.5);
  let rim = pow(1.0 - facing, 1.45);
  let surfaceNormal = normalize(bm_in.vNormal);
  let structure = textureSample(uBillboard, uBillboard_sampler, vec2f(surfaceNormal.x * 0.5 + 0.5, surfaceNormal.y * 0.5 + 0.5)).w;
  let textured = 0.55 + structure * 0.45;
  return vec4f(bm_in.vColor * ((0.45 + core * 1.2 + rim * 0.45) * textured), bm_in.vAlpha * (0.4 + core * 0.5 + rim * 0.24) * textured);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iColor: 'vec3', iAlpha: 'float', iRotation: 'float', iPhase: 'float' },
  uniforms: { uBillboard: 'sampler2D', uViewProj: 'mat4', uCameraPosition: 'vec3', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iColor","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iAlpha","type":"float","location":5,"size":1,"divisor":1},{"name":"iRotation","type":"float","location":6,"size":1,"divisor":1},{"name":"iPhase","type":"float","location":7,"size":1,"divisor":1}],"uniforms":[{"name":"uBillboard","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCameraPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76}],"uniformBlockSize":80},

};

export default traversalGlowShader;
