/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const townPropShadowShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iCenter: 'vec3'; iSize: 'vec2'; iUvRect: 'vec4'; iYaw: 'float'; iCurvature: 'float'; iTile: 'float' }, { uLightViewProj: 'mat4'; uAtlas: 'sampler2D'; uCutoff: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uLightViewProj : mat4x4f,
  uCutoff : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iCenter : vec3f,
  @location(3) iSize : vec2f,
  @location(4) iUvRect : vec4f,
  @location(5) iYaw : f32,
  @location(6) iCurvature : f32,
  @location(7) iTile : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vWorld : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let bend = max(bm_in.iCurvature * 2.4, 0.001);
  let angle = bm_in.aPosition.x * bend;
  let lean = 0.12;
  let localX = sin(angle) / bend * bm_in.iSize.x;
  let localY = bm_in.aPosition.y * bm_in.iSize.y;
  let localZ = (cos(angle) - 1.0) / bend * bm_in.iSize.x - bm_in.aPosition.y * bm_in.iSize.y * lean + bm_in.iTile * 0.0;
  let frontNormal = normalize(vec3f(sin(angle), cos(angle) * lean, cos(angle)));
  let yawCos = cos(bm_in.iYaw);
  let yawSin = sin(bm_in.iYaw);
  let rotated = vec3f(yawCos * localX + yawSin * localZ, localY, -yawSin * localX + yawCos * localZ);
  let rotatedFrontNormal = normalize(vec3f(yawCos * frontNormal.x + yawSin * frontNormal.z, frontNormal.y, -yawSin * frontNormal.x + yawCos * frontNormal.z));
  let surfaceNormal = rotatedFrontNormal * bm_in.aPosition.z;
  let thickness = 0.012 + bm_in.iSize.x * 0.012;
  let world = bm_in.iCenter + rotated + surfaceNormal * thickness;
  bm_out.vUv = bm_in.iUvRect.xy + bm_in.aUv * vec2f(bm_in.iUvRect.z, bm_in.iUvRect.w);
  bm_out.vWorld = world;
  bm_out.bm_position = bm_u.uLightViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  if (textureSample(uAtlas, uAtlas_sampler, bm_in.vUv).w < bm_u.uCutoff) {
    discard;
  }
  let clip = bm_u.uLightViewProj * vec4f(bm_in.vWorld, 1.0);
  let depth = clamp(clip.z / clip.w * 0.5 + 0.5, 0.0, 1.0);
  let scaled = depth * 255.0;
  return vec4f(floor(scaled) / 255.0, fract(scaled), depth, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iCenter: 'vec3', iSize: 'vec2', iUvRect: 'vec4', iYaw: 'float', iCurvature: 'float', iTile: 'float' },
  uniforms: { uLightViewProj: 'mat4', uAtlas: 'sampler2D', uCutoff: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iCenter","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iSize","type":"vec2","location":3,"size":2,"divisor":1},{"name":"iUvRect","type":"vec4","location":4,"size":4,"divisor":1},{"name":"iYaw","type":"float","location":5,"size":1,"divisor":1},{"name":"iCurvature","type":"float","location":6,"size":1,"divisor":1},{"name":"iTile","type":"float","location":7,"size":1,"divisor":1}],"uniforms":[{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":64}],"uniformBlockSize":80},

};

export default townPropShadowShader;
