/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const townSpriteShadowShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2'; aShell: 'float' }, { iCenter: 'vec3'; iSize: 'vec2'; iUvRect: 'vec4'; iTint: 'vec4'; iFacing: 'vec3' }, { uLightViewProj: 'mat4'; uRight: 'vec3'; uUp: 'vec3'; uAtlas: 'sampler2D'; uCutoff: 'float'; uColorKey: 'vec3'; uUseColorKey: 'float'; uStandeeThickness: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uLightViewProj : mat4x4f,
  uRight : vec3f,
  uUp : vec3f,
  uCutoff : f32,
  uColorKey : vec3f,
  uUseColorKey : f32,
  uStandeeThickness : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) aShell : f32,
  @location(3) iCenter : vec3f,
  @location(4) iSize : vec2f,
  @location(5) iUvRect : vec4f,
  @location(6) iTint : vec4f,
  @location(7) iFacing : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vTintAlpha : f32,
  @location(2) vWorld : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let billboardNormal = normalize(cross(bm_u.uRight, bm_u.uUp));
  let facingNoop = bm_in.iFacing.x * 0.0;
  let world = bm_in.iCenter + bm_u.uRight * (bm_in.aPosition.x * bm_in.iSize.x + facingNoop) + bm_u.uUp * (bm_in.aPosition.y * bm_in.iSize.y) + billboardNormal * (bm_in.aShell * bm_u.uStandeeThickness * 0.5);
  bm_out.vUv = bm_in.iUvRect.xy + bm_in.aUv * vec2f(bm_in.iUvRect.z, bm_in.iUvRect.w);
  bm_out.vTintAlpha = bm_in.iTint.w;
  bm_out.vWorld = world;
  bm_out.bm_position = bm_u.uLightViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  let keyed = (1.0 - smoothstep(0.015, 0.075, length(texel.xyz - bm_u.uColorKey))) * clamp(bm_u.uUseColorKey, 0.0, 1.0);
  let alpha = texel.w * (1.0 - keyed) * bm_in.vTintAlpha;
  if (alpha < bm_u.uCutoff) {
    discard;
  }
  let clip = bm_u.uLightViewProj * vec4f(bm_in.vWorld, 1.0);
  let depth = clamp(clip.z / clip.w * 0.5 + 0.5, 0.0, 1.0);
  let scaled = depth * 255.0;
  let high = floor(scaled) / 255.0;
  let low = fract(scaled);
  return vec4f(high, low, depth, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2', aShell: 'float' },
  instanceAttributes: { iCenter: 'vec3', iSize: 'vec2', iUvRect: 'vec4', iTint: 'vec4', iFacing: 'vec3' },
  uniforms: { uLightViewProj: 'mat4', uRight: 'vec3', uUp: 'vec3', uAtlas: 'sampler2D', uCutoff: 'float', uColorKey: 'vec3', uUseColorKey: 'float', uStandeeThickness: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"aShell","type":"float","location":2,"size":1,"divisor":0},{"name":"iCenter","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iSize","type":"vec2","location":4,"size":2,"divisor":1},{"name":"iUvRect","type":"vec4","location":5,"size":4,"divisor":1},{"name":"iTint","type":"vec4","location":6,"size":4,"divisor":1},{"name":"iFacing","type":"vec3","location":7,"size":3,"divisor":1}],"uniforms":[{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uRight","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uUp","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":92},{"name":"uColorKey","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uUseColorKey","type":"float","kind":"1f","size":1,"offset":108},{"name":"uStandeeThickness","type":"float","kind":"1f","size":1,"offset":112}],"uniformBlockSize":128},

};

export default townSpriteShadowShader;
