export type AntikyCliErrorCode =
  | 'ANTIKY_ARGUMENT_INVALID'
  | 'ANTIKY_PROJECT_AMBIGUOUS'
  | 'ANTIKY_PROJECT_CREATE_FAILED'
  | 'ANTIKY_PROJECT_DIRECTORY_INVALID'
  | 'ANTIKY_PROJECT_EXISTS'
  | 'ANTIKY_PROJECT_INIT_INTERRUPTED'
  | 'ANTIKY_PROJECT_INCOMPATIBLE'
  | 'ANTIKY_PROJECT_INVALID'
  | 'ANTIKY_PROJECT_NOT_FILE'
  | 'ANTIKY_PROJECT_NOT_FOUND'
  | 'ANTIKY_PROJECT_NAME_INVALID'
  | 'ANTIKY_PROJECT_PATH_ESCAPE'
  | 'ANTIKY_PROJECT_TOO_LARGE'
  | 'ANTIKY_PORT_BUSY'
  | 'ANTIKY_CHILD_START_FAILED'
  | 'ANTIKY_CHILD_STOP_FAILED'
  | 'ANTIKY_INTERNAL_ERROR'
  | 'ANTIKY_SESSION_UNAVAILABLE'
  | 'ANTIKY_STUDIO_UNAVAILABLE'
  | 'ANTIKY_UNAUTHORIZED'
  | 'ANTIKY_RUNTIME_UNAVAILABLE'
  | 'ANTIKY_ACTION_BUSY'
  | 'ANTIKY_ACTION_TIMEOUT'
  | 'ANTIKY_ACTION_STALE'
  | 'ANTIKY_CAPTURE_INVALID'
  | 'ANTIKY_CAPTURE_SAVE_FAILED'
  | 'ANTIKY_RUNTIME_STALE'
  | 'ANTIKY_PUBLICATION_STALE';

export class AntikyCliError extends Error {
  constructor(
    readonly code: AntikyCliErrorCode,
    message: string,
    readonly path?: string,
  ) {
    super(message);
    this.name = 'AntikyCliError';
  }
}
