/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const auroraShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float'; uPointer: 'vec2' }> = {
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
  uPointer : vec2f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn cosinePalette(t : f32, a : vec3f, b : vec3f, c : vec3f, d : vec3f) -> vec3f {
  let phase = (c * t + d) * 6.28318;
  return a + vec3f(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
fn hash21(p : vec2f) -> f32 {
  return fract(sin(dot(p, vec2f(127.1, 311.7))) * 43758.5453);
}
fn vnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  let a = hash21(cell);
  let b = hash21(cell + vec2f(1.0, 0.0));
  let c = hash21(cell + vec2f(0.0, 1.0));
  let d = hash21(cell + vec2f(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
fn fbm2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn filmGrain(uv : vec2f, time : f32) -> f32 {
  return hash21(uv * 997.0 + vec2f(fract(time * 13.37) * 100.0, 0.0)) - 0.5;
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn gnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * f.x * (f.x * (f.x * 6.0 - 15.0) + 10.0), f.y * f.y * f.y * (f.y * (f.y * 6.0 - 15.0) + 10.0));
  let ga = hash22(cell) * 2.0 - vec2f(1.0, 1.0);
  let gb = hash22(cell + vec2f(1.0, 0.0)) * 2.0 - vec2f(1.0, 1.0);
  let gc = hash22(cell + vec2f(0.0, 1.0)) * 2.0 - vec2f(1.0, 1.0);
  let gd = hash22(cell + vec2f(1.0, 1.0)) * 2.0 - vec2f(1.0, 1.0);
  let va = dot(ga, f);
  let vb = dot(gb, f - vec2f(1.0, 0.0));
  let vc = dot(gc, f - vec2f(0.0, 1.0));
  let vd = dot(gd, f - vec2f(1.0, 1.0));
  return mix(mix(va, vb, u.x), mix(vc, vd, u.x), u.y) * 0.7 + 0.5;
}
fn turbulence2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * abs(gnoise2(p * frequency) * 2.0 - 1.0);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn auroraCurtain(p : vec2f, offset : f32, phase : f32, time : f32) -> f32 {
  let warp = fbm2(vec2f(p.x * 1.15 + phase, time * 0.055 + phase), 5.0);
  let center = offset + sin(p.x * 1.65 + phase + time * 0.16) * 0.11 + (warp - 0.5) * 0.42;
  let distance = abs(p.y - center);
  let folds = turbulence2(vec2f(p.x * 3.3 + phase, time * 0.075), 4.0);
  let sheet = 1.0 - smoothstep(0.025, 0.22 + folds * 0.08, distance);
  let striation = 0.34 + pow(max(sin(p.x * 24.0 + warp * 8.0 + phase), 0.0), 5.0) * 0.78;
  let vertical = smoothstep(-0.62, 0.04, p.y) * (1.0 - smoothstep(0.7, 1.15, p.y));
  return sheet * striation * vertical;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect + (bm_u.uPointer.x - 0.5) * 0.08, bm_in.vUv.y - 0.5 + (bm_u.uPointer.y - 0.5) * 0.035) * 2.35;
  let horizon = smoothstep(-0.72, 0.85, p.y);
  let sky = vec3f(0.002, 0.006, 0.03) + vec3f(0.015, 0.035, 0.14) * horizon + vec3f(0.12, 0.025, 0.16) * (pow(horizon, 4.0) * 0.16);
  let starGrid = p * 86.0;
  let starCell = vec2f(floor(starGrid.x), floor(starGrid.y));
  let starLocal = vec2f(fract(starGrid.x) - 0.5, fract(starGrid.y) - 0.5);
  let starPoint = (hash22(starCell) - vec2f(0.5, 0.5)) * 0.68;
  let starSeed = hash21(starCell);
  let starDistance = length(starLocal - starPoint);
  let stars = (1.0 - smoothstep(0.018, 0.075, starDistance)) * smoothstep(0.955, 0.998, starSeed) * (0.58 + sin(bm_u.uTime * (0.7 + starSeed * 2.6) + starSeed * 90.0) * 0.4) * smoothstep(-0.45, 0.1, p.y);
  let milky = turbulence2(vec2f(p.x * 0.72 + p.y * 0.38 + 2.4, p.y * 1.4 - p.x * 0.12), 5.0) * smoothstep(-0.1, 0.62, p.y);
  let curtainA = auroraCurtain(p, 0.22, 0.3, bm_u.uTime);
  let curtainB = auroraCurtain(p, 0.4, 2.1, bm_u.uTime) * 0.78;
  let curtainC = auroraCurtain(p, 0.58, 4.4, bm_u.uTime) * 0.52;
  let palette = cosinePalette(p.x * 0.09 + bm_u.uTime * 0.012, vec3f(0.18, 0.34, 0.38), vec3f(0.2, 0.34, 0.3), vec3f(1.0, 1.0, 1.0), vec3f(0.08, 0.18, 0.52));
  let aurora = palette * (curtainA * 1.55) + vec3f(0.04, 1.2, 0.78) * curtainB + vec3f(0.62, 0.12, 1.15) * curtainC;
  let farHeight = -0.39 + fbm2(vec2f(p.x * 0.62 + 7.1, 1.3), 5.0) * 0.34;
  let nearHeight = -0.67 + fbm2(vec2f(p.x * 1.12 + 2.4, 3.7), 5.0) * 0.5;
  let farMountain = 1.0 - smoothstep(farHeight, farHeight + 0.025, p.y);
  let nearMountain = 1.0 - smoothstep(nearHeight, nearHeight + 0.03, p.y);
  let snowLine = (1.0 - smoothstep(nearHeight - 0.055, nearHeight + 0.018, p.y)) * smoothstep(nearHeight - 0.13, nearHeight - 0.035, p.y);
  let ripple = sin(p.y * 82.0 + p.x * 5.0 - bm_u.uTime * 1.2) * 0.012;
  let reflectedPoint = vec2f(p.x + ripple, -p.y - 0.5);
  let reflection = auroraCurtain(reflectedPoint, 0.22, 0.3, bm_u.uTime) + auroraCurtain(reflectedPoint, 0.4, 2.1, bm_u.uTime) * 0.55;
  let waterMask = 1.0 - smoothstep(-0.73, -0.67, p.y);
  let water = vec3f(0.004, 0.018, 0.055) + palette * (reflection * 0.22 * (0.55 + sin(p.y * 110.0) * 0.18)) + vec3f(0.06, 0.17, 0.27) * (abs(ripple) * 4.0);
  let skyColor = sky + vec3f(0.74, 0.86, 1.2) * stars + vec3f(0.08, 0.055, 0.2) * (milky * 0.22) + aurora;
  let mountains = (skyColor * (1.0 - farMountain) + vec3f(0.025, 0.055, 0.11) * farMountain) * (1.0 - nearMountain) + vec3f(0.008, 0.016, 0.035) * nearMountain + vec3f(0.26, 0.36, 0.52) * (snowLine * 0.38);
  let composed = mountains * (1.0 - waterMask) + water * waterMask;
  let grain = filmGrain(bm_in.vUv, bm_u.uTime) * 0.012;
  return vec4f(tonemapACES(composed + vec3f(grain, grain, grain)), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float', uPointer: 'vec2' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4},{"name":"uPointer","type":"vec2","kind":"2fv","size":2,"offset":8}],"uniformBlockSize":16},

};

export default auroraShader;
