/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const modelDepthShader: CompiledShader<{ aPosition: 'vec3' }, { iOffset: 'vec3'; iScale: 'float'; iRotation: 'vec3' }, { uLightViewProj: 'mat4'; uLightPosition: 'vec3'; uShadowRange: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uLightViewProj : mat4x4f,
  uLightPosition : vec3f,
  uShadowRange : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iOffset : vec3f,
  @location(2) iScale : f32,
  @location(3) iRotation : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
}
fn shadowDepth(worldPos : vec3f, lightPos : vec3f, range : f32) -> f32 {
  return distance(worldPos, lightPos) / range;
}
fn rotateModel(value : vec3f, rotation : vec3f) -> vec3f {
  let cosZ = cos(rotation.z);
  let sinZ = sin(rotation.z);
  let aroundZ = vec3f(value.x * cosZ - value.y * sinZ, value.x * sinZ + value.y * cosZ, value.z);
  let cosX = cos(rotation.x);
  let sinX = sin(rotation.x);
  let aroundX = vec3f(aroundZ.x, aroundZ.y * cosX - aroundZ.z * sinX, aroundZ.y * sinX + aroundZ.z * cosX);
  let cosY = cos(rotation.y);
  let sinY = sin(rotation.y);
  return vec3f(aroundX.x * cosY - aroundX.z * sinY, aroundX.y, aroundX.x * sinY + aroundX.z * cosY);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = rotateModel(bm_in.aPosition * bm_in.iScale, bm_in.iRotation) + bm_in.iOffset;
  bm_out.vWorld = world;
  bm_out.bm_position = bm_u.uLightViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return vec4f(shadowDepth(bm_in.vWorld, bm_u.uLightPosition, bm_u.uShadowRange), 0.0, 0.0, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'float', iRotation: 'vec3' },
  uniforms: { uLightViewProj: 'mat4', uLightPosition: 'vec3', uShadowRange: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iScale","type":"float","location":2,"size":1,"divisor":1},{"name":"iRotation","type":"vec3","location":3,"size":3,"divisor":1}],"uniforms":[{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uLightPosition","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uShadowRange","type":"float","kind":"1f","size":1,"offset":76}],"uniformBlockSize":80},

};

export default modelDepthShader;
