import { loadTexture, type BroMetalTexture, type Renderer } from 'brometal';

const DETAIL_NORMAL_URL = new URL(
  '../assets/textures/detail-normal-512.png',
  import.meta.url,
).href;

/**
 * The tiling detail normal every surface in this demo projects over itself.
 *
 * Generated by `packages/demos/scripts/build-detail-normal.mjs`, which writes the same bytes into
 * each demo. It carries no colour and no identity — it exists so a flat surface stops reading as one
 * constant when a light moves across it, which is the single largest reason these demos read as
 * plastic. The tile rate and how much of it each surface shows are decided in the shaders.
 *
 * `wrap: 'repeat'` is the whole point: the texture is projected at roughly four world units per tile
 * and would clamp to a smear without it. Mips and anisotropy are on because this is sampled at a
 * high rate across surfaces seen at grazing angles, which is exactly the case trilinear alone
 * handles badly.
 */
export function loadDetailNormal(renderer: Renderer): Promise<BroMetalTexture> {
  return loadTexture(renderer, DETAIL_NORMAL_URL, {
    wrap: 'repeat',
    filter: 'smooth',
    anisotropy: 8,
    flipY: false,
  });
}
