/**
 * Diffuse irradiance from `dikhololo-night`, projected onto the first nine spherical harmonics.
 *
 * Generated by `packages/demos/scripts/bake-sh9-irradiance.mjs`. Do not hand-edit: re-run the bake.
 *
 * Dikhololo Night — https://polyhaven.com/a/dikhololo_night
 * CC0. Source HDRI sha256 6861489f983cdc0c22435b781a348717
 *
 * The convolution and basis constants are already folded in, so reconstructing irradiance for a
 * surface normal is nine multiply-adds and nothing else:
 *
 *   E(n) = c0
 *        + c1*n.y + c2*n.z + c3*n.x
 *        + c4*n.x*n.y + c5*n.y*n.z + c6*(3*n.z*n.z - 1) + c7*n.x*n.z + c8*(n.x*n.x - n.y*n.y)
 *
 * The result is reflected radiance for an albedo of 1, which is what every material shader here
 * already multiplies its albedo by — so it drops straight in where the flat ambient constant was.
 */
export const RELIQUARY_SH9_IRRADIANCE = Object.freeze([
  [0.096238, 0.082281, 0.067734],
  [0.047987, 0.049811, 0.04914],
  [0.016552, 0.015559, 0.013753],
  [-0.046398, -0.041868, -0.034533],
  [-0.017514, -0.01777, -0.016932],
  [0.011933, 0.010282, 0.008408],
  [0.011713, 0.007272, 0.003703],
  [0.012883, 0.006291, 0.001895],
  [0.019253, 0.015642, 0.010643],
] as const);
