import type { TextureSource } from '@antiky/framework/render-driver';

const VFX_BILLBOARD_URL = new URL('../assets/textures/vfx-billboard-256.png', import.meta.url).href;

/**
 * The soft billboard the relay glows are textured with.
 *
 * Generated by `packages/demos/scripts/build-vfx-billboard.mjs`: white, with the structure in the
 * alpha, so a shader tints it with whatever colour the effect already carries.
 *
 * `wrap: 'clamp'` because this is one sprite, not a tile. Repeating would wrap the rim's zero alpha
 * round to the opposite edge and cut a hard line across every glow.
 */
export const VFX_BILLBOARD_TEXTURE: TextureSource = Object.freeze({
  url: VFX_BILLBOARD_URL,
  options: { wrap: 'clamp', filter: 'smooth', anisotropy: 4, flipY: false } as const,
});
