/**
 * Diffuse irradiance from `venice-sunset`, projected onto the first nine spherical harmonics.
 *
 * Generated by `packages/demos/scripts/bake/sh9-irradiance.mjs`. Do not hand-edit: re-run the bake.
 *
 * Venice Sunset — https://polyhaven.com/a/venice_sunset
 * CC0. Source HDRI sha256 92fe2b29b1957828fb8925a57633540b
 *
 * The convolution and basis constants are already folded in, so reconstructing irradiance for a
 * surface normal is nine multiply-adds and nothing else:
 *
 *   E(n) = c0
 *        + c1*n.y + c2*n.z + c3*n.x
 *        + c4*n.x*n.y + c5*n.y*n.z + c6*(3*n.z*n.z - 1) + c7*n.x*n.z + c8*(n.x*n.x - n.y*n.y)
 *
 * The result is reflected radiance for an albedo of 1, which is what every material shader here
 * already multiplies its albedo by — so it drops straight in where the flat ambient constant was.
 */
export const TOWN_SH9_IRRADIANCE = Object.freeze([
  [0.507281, 0.478675, 0.609372],
  [0.210707, 0.279894, 0.464457],
  [-0.40531, -0.267146, -0.212987],
  [0.252621, 0.12919, 0.061927],
  [0.08895, 0.053635, 0.027596],
  [-0.133589, -0.095755, -0.079377],
  [0.058461, 0.025586, 0.003115],
  [-0.266874, -0.134303, -0.078308],
  [0.078048, 0.041787, 0.010477],
] as const);
