/* Generated by scripts/intake-quaternius-ships.mjs. Do not edit. */

export const SHIP_FOOTPRINTS = {
  "schemaVersion": 1,
  "derivation": "Maximum hypot(position.x * runtimeScale.x, position.z * runtimeScale.z) over every BroMetal-parsed shipped vertex",
  "ships": {
    "player": {
      "asset": "spitfire-blue.glb",
      "scale": {
        "x": 0.17,
        "z": 0.22
      },
      "span": {
        "width": 1.7890270137786866,
        "length": 1.6573277139663696
      },
      "radialRadius": 1.0006254347740144
    },
    "rusher": {
      "asset": "striker-red.glb",
      "scale": {
        "x": 0.28,
        "z": 0.26
      },
      "span": {
        "width": 1.4094126319885256,
        "length": 2.1908034229278566
      },
      "radialRadius": 1.3376796776487205
    },
    "gunner": {
      "asset": "omen-orange.glb",
      "scale": {
        "x": 0.15,
        "z": 0.16
      },
      "span": {
        "width": 1.9176615715026855,
        "length": 2.013031311035156
      },
      "radialRadius": 1.3866019004646903
    },
    "shieldAnchor": {
      "asset": "imperial-red.glb",
      "scale": {
        "x": 0.25,
        "z": 0.14
      },
      "span": {
        "width": 1.932380199432373,
        "length": 2.596773920059204
      },
      "radialRadius": 1.7511885889646661
    },
    "warden": {
      "asset": "executioner-red.glb",
      "scale": {
        "x": 0.48,
        "z": 0.5
      },
      "span": {
        "width": 4.810618286132812,
        "length": 4.601085543632507
      },
      "radialRadius": 3.117963690626425
    }
  }
} as const;
