/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const solarForgeShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float'; uPointer: 'vec2' }> = {
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
  uPointer : vec2f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn hash21(p : vec2f) -> f32 {
  return fract(sin(dot(p, vec2f(127.1, 311.7))) * 43758.5453);
}
fn vnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  let a = hash21(cell);
  let b = hash21(cell + vec2f(1.0, 0.0));
  let c = hash21(cell + vec2f(0.0, 1.0));
  let d = hash21(cell + vec2f(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
fn fbm2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn gnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * f.x * (f.x * (f.x * 6.0 - 15.0) + 10.0), f.y * f.y * f.y * (f.y * (f.y * 6.0 - 15.0) + 10.0));
  let ga = hash22(cell) * 2.0 - vec2f(1.0, 1.0);
  let gb = hash22(cell + vec2f(1.0, 0.0)) * 2.0 - vec2f(1.0, 1.0);
  let gc = hash22(cell + vec2f(0.0, 1.0)) * 2.0 - vec2f(1.0, 1.0);
  let gd = hash22(cell + vec2f(1.0, 1.0)) * 2.0 - vec2f(1.0, 1.0);
  let va = dot(ga, f);
  let vb = dot(gb, f - vec2f(1.0, 0.0));
  let vc = dot(gc, f - vec2f(0.0, 1.0));
  let vd = dot(gd, f - vec2f(1.0, 1.0));
  return mix(mix(va, vb, u.x), mix(vc, vd, u.x), u.y) * 0.7 + 0.5;
}
fn turbulence2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * abs(gnoise2(p * frequency) * 2.0 - 1.0);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let pointer = vec2f(bm_u.uPointer.x - 0.5, bm_u.uPointer.y - 0.5);
  let p = rotate2(vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect - pointer.x * 0.08, bm_in.vUv.y - 0.5 - pointer.y * 0.045) * 2.05, -0.08);
  let center = p - vec2f(0.08, -0.015);
  let radius = length(center);
  let angle = atan2(center.y, center.x);
  let starGrid = p * 92.0;
  let starCell = vec2f(floor(starGrid.x), floor(starGrid.y));
  let starLocal = vec2f(fract(starGrid.x) - 0.5, fract(starGrid.y) - 0.5);
  let starPoint = (hash22(starCell) - vec2f(0.5, 0.5)) * 0.68;
  let starSeed = hash21(starCell);
  let starDistance = length(starLocal - starPoint);
  let starCore = 1.0 - smoothstep(0.014, 0.062, starDistance);
  let starGlint = 0.0025 / max(starDistance, 0.018);
  let star = (starCore + starGlint * 0.08) * smoothstep(0.965, 0.998, starSeed) * (0.45 + sin(bm_u.uTime * (0.8 + starSeed * 2.2) + starSeed * 80.0) * 0.35) * smoothstep(0.52, 0.72, radius);
  let nebula = fbm2(p * 1.45 + vec2f(bm_u.uTime * 0.014, -bm_u.uTime * 0.009), 5.0);
  let dust = turbulence2(p * 3.1 + vec2f(-bm_u.uTime * 0.025, bm_u.uTime * 0.018), 4.0);
  let background = vec3f(0.0015, 0.002, 0.012) + vec3f(0.024, 0.008, 0.07) * (nebula * nebula * 0.8) + vec3f(0.006, 0.025, 0.07) * (dust * 0.32) + vec3f(0.8, 0.9, 1.3) * star;
  let angularFlow = fbm2(vec2f(angle * 1.7 + bm_u.uTime * 0.12, radius * 5.8 - bm_u.uTime * 0.09), 5.0);
  let flareNoise = turbulence2(vec2f(angle * 2.8 - bm_u.uTime * 0.17, radius * 7.2 + bm_u.uTime * 0.06), 5.0);
  let photonRadius = 0.405 + (angularFlow - 0.5) * 0.035;
  let photonRing = 0.018 / max(abs(radius - photonRadius), 0.006);
  let innerRim = smoothstep(0.425, 0.398, radius) - smoothstep(0.385, 0.36, radius);
  let coronaRadius = 0.52 + flareNoise * 0.11 + sin(angle * 7.0 - bm_u.uTime * 0.7) * 0.025;
  let corona = 0.025 / max(abs(radius - coronaRadius), 0.018) * smoothstep(0.78, 0.38, radius);
  let rays = pow(max(sin(angle * 17.0 + angularFlow * 7.0 - bm_u.uTime * 0.6), 0.0), 10.0) * smoothstep(0.98, 0.46, radius) * smoothstep(0.43, 0.58, radius);
  let diskPoint = vec2f(center.x, center.y * 5.4);
  let diskRadius = length(diskPoint);
  let diskNoise = fbm2(vec2f(angle * 2.2 + bm_u.uTime * 0.2, diskRadius * 5.2), 4.0);
  let disk = smoothstep(0.11, 0.015, abs(diskRadius - 0.72 - diskNoise * 0.09)) * smoothstep(1.08, 0.48, diskRadius);
  let frontDisk = disk * smoothstep(-0.03, 0.07, center.y);
  let backDisk = disk * smoothstep(0.08, -0.03, center.y) * 0.42;
  let approachingDisk = frontDisk * smoothstep(-0.72, 0.58, center.x);
  let recedingDisk = frontDisk - approachingDisk;
  let coreMask = smoothstep(0.405, 0.365, radius);
  let lensHalo = smoothstep(0.72, 0.4, radius) * smoothstep(0.36, 0.42, radius);
  let heat = vec3f(1.65, 0.16, 0.008) * (corona * 0.18 + rays * 1.4) + vec3f(2.4, 0.72, 0.08) * (photonRing * 0.42 + innerRim * 2.5) + vec3f(1.6, 0.36, 0.025) * (backDisk * 1.2) + vec3f(2.75, 1.12, 0.22) * (recedingDisk * 2.25) + vec3f(1.45, 1.72, 2.8) * (approachingDisk * 1.65) + vec3f(0.3, 0.12, 0.7) * (lensHalo * 0.22);
  let blackCore = mix(vec3f(0.001, 0.0015, 0.004), vec3f(0.006, 0.001, 0.002), clamp(radius * 2.0, 0.0, 1.0));
  let color = background * (1.0 - coreMask) + blackCore * coreMask + heat;
  return vec4f(tonemapACES(color), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float', uPointer: 'vec2' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4},{"name":"uPointer","type":"vec2","kind":"2fv","size":2,"offset":8}],"uniformBlockSize":16},

};

export default solarForgeShader;
